optimize core library

diff --git a/base b/base
--- a/base
+++ b/base
@@ -146,69 +146,69 @@ return 1
 esac
 }
 COLORS=$(tput colors 2>/dev/null||echo 0)
-CC_RESET=$'\033[0m'
-CC_RESET_FG=$'\033[39m'
-CC_RESET_BG=$'\033[49m'
-CC_INTENSITY_BOLD=$'\033[1m'
-CC_INTENSITY_LIGHT=$'\033[2m'
-CC_INTENSITY_OFF=$'\033[22m'
-CC_ITALIC=$'\033[3m'
-CC_ITALIC_OFF=$'\033[23m'
-CC_UNDERLINE=$'\033[4m'
-CC_UNDERLINE_OFF=$'\033[24m'
-CC_INVERSE=$'\033[7m'
-CC_INVERSE_OFF=$'\033[27m'
-CC_DASHED=$'\033[9m'
-CC_DASHED_OFF=$'\033[29m'
-CC_BLACK=$'\033[30m'
-CC_RED=$'\033[31m'
-CC_GREEN=$'\033[32m'
-CC_YELLOW=$'\033[33m'
-CC_BLUE=$'\033[34m'
-CC_MAGENTA=$'\033[35m'
-CC_CYAN=$'\033[36m'
-CC_WHITE=$'\033[37m'
-CC_BLACK_BOLD=$'\033[90m'
-CC_RED_BOLD=$'\033[91m'
-CC_GREEN_BOLD=$'\033[92m'
-CC_YELLOW_BOLD=$'\033[93m'
-CC_BLUE_BOLD=$'\033[94m'
-CC_MAGENTA_BOLD=$'\033[95m'
-CC_CYAN_BOLD=$'\033[96m'
-CC_WHITE_BOLD=$'\033[97m'
-CC_BLACK_BG=$'\033[40m'
-CC_RED_BG=$'\033[41m'
-CC_GREEN_BG=$'\033[42m'
-CC_YELLOW_BG=$'\033[43m'
-CC_BLUE_BG=$'\033[44m'
-CC_MAGENTA_BG=$'\033[45m'
-CC_CYAN_BG=$'\033[46m'
-CC_BLACK_BOLD_BG=$'\033[100m'
-CC_RED_BOLD_BG=$'\033[101m'
-CC_GREEN_BOLD_BG=$'\033[102m'
-CC_YELLOW_BOLD_BG=$'\033[103m'
-CC_BLUE_BOLD_BG=$'\033[104m'
-CC_MAGENTA_BOLD_BG=$'\033[105m'
-CC_CYAN_BOLD_BG=$'\033[106m'
+CC_RESET=$'\e[0m'
+CC_RESET_FG=$'\e[39m'
+CC_RESET_BG=$'\e[49m'
+CC_INTENSITY_BOLD=$'\e[1m'
+CC_INTENSITY_LIGHT=$'\e[2m'
+CC_INTENSITY_OFF=$'\e[22m'
+CC_ITALIC=$'\e[3m'
+CC_ITALIC_OFF=$'\e[23m'
+CC_UNDERLINE=$'\e[4m'
+CC_UNDERLINE_OFF=$'\e[24m'
+CC_INVERSE=$'\e[7m'
+CC_INVERSE_OFF=$'\e[27m'
+CC_DASHED=$'\e[9m'
+CC_DASHED_OFF=$'\e[29m'
+CC_BLACK=$'\e[30m'
+CC_RED=$'\e[31m'
+CC_GREEN=$'\e[32m'
+CC_YELLOW=$'\e[33m'
+CC_BLUE=$'\e[34m'
+CC_MAGENTA=$'\e[35m'
+CC_CYAN=$'\e[36m'
+CC_WHITE=$'\e[37m'
+CC_BLACK_BOLD=$'\e[90m'
+CC_RED_BOLD=$'\e[91m'
+CC_GREEN_BOLD=$'\e[92m'
+CC_YELLOW_BOLD=$'\e[93m'
+CC_BLUE_BOLD=$'\e[94m'
+CC_MAGENTA_BOLD=$'\e[95m'
+CC_CYAN_BOLD=$'\e[96m'
+CC_WHITE_BOLD=$'\e[97m'
+CC_BLACK_BG=$'\e[40m'
+CC_RED_BG=$'\e[41m'
+CC_GREEN_BG=$'\e[42m'
+CC_YELLOW_BG=$'\e[43m'
+CC_BLUE_BG=$'\e[44m'
+CC_MAGENTA_BG=$'\e[45m'
+CC_CYAN_BG=$'\e[46m'
+CC_BLACK_BOLD_BG=$'\e[100m'
+CC_RED_BOLD_BG=$'\e[101m'
+CC_GREEN_BOLD_BG=$'\e[102m'
+CC_YELLOW_BOLD_BG=$'\e[103m'
+CC_BLUE_BOLD_BG=$'\e[104m'
+CC_MAGENTA_BOLD_BG=$'\e[105m'
+CC_CYAN_BOLD_BG=$'\e[106m'
 color_256(){
 is integer --name=arguments --max=1 --die -- $#
 local num
 num="$(check integer --name=num "$1" --sanitize --min=0 --max=255 --die)"
-echo $'\033[38;5;'"$num"'m'
+echo $'\e[38;5;'"$num"'m'
 }
 color_256_bg(){
 is integer --name=arguments --max=1 --die -- $#
 local num
 num="$(check integer --name=num "$1" --sanitize --min=0 --max=255 --die)"
-echo $'\033[48;5;'"$num"'m'
+echo $'\e[48;5;'"$num"'m'
 }
-CC_CRITICAL=$'\033[1;45m'
-CC_ERROR=$'\033[1;31m'
-CC_WARN=$'\033[1;33m'
-CC_NOTICE=$'\033[1;34m'
-CC_OK=$'\033[1;32m'
-CC_HEADING=$'\033[44m'
-CC_INVERS=$'\033[7m'
+CC_CRITICAL=$'\e[1;45m'
+CC_ERROR=$'\e[1;31m'
+CC_WARN=$'\e[1;33m'
+CC_NOTICE=$'\e[1;34m'
+CC_OK=$'\e[1;32m'
+CC_HEADING=$'\e[44m'
+CC_INVERS=$'\e[7m'
 color_table(){
 is integer --name=arguments --max=0 --die -- $#
 echo "Basic Colors:"
@@ -231,14 +231,14 @@ local rows=15
 for c in $(seq 0 "$cols");do
 for r in $(seq 0 "$rows");do
 num=$((r*cols+c))
-printf "\t$(color_256 "$num")FG $num"
+printf '%s' "\t$(color_256 "$num")FG $num"
 done
 echo ""
 done
 for c in $(seq 0 "$cols");do
 for r in $(seq 0 "$rows");do
 num=$((r*cols+c))
-printf "\t$(color_256_bg "$num")BG $num$CC_RESET"
+printf '%s' "\t$(color_256_bg "$num")BG $num$CC_RESET"
 done
 echo ""
 done
@@ -265,7 +265,7 @@ is integer --name=arguments --max=2 --die -- $#
 local start end
 end="${2:-$(now)}"
 is integer -- "$1"&&start="$1"||start=$(date -d "$1" +%s)||die "Date format '$1' not parsable!"
-is integer -- "$end"&&end="$end"||end=$(date -d "$end" +%s)||die "Date format '$2' not parsable!"
+is integer -- "$end"||end=$(date -d "$end" +%s)||die "Date format '$2' not parsable!"
 printf '%s' $((end-start))
 }
 date_format(){
@@ -388,7 +388,7 @@ source gettext.sh
 _deprecated(){
 IFS=$' \t\n' read -r line func file <<<"$(caller 1)"
 local message="DEPRECATED: ${FUNCNAME[1]} at $func in $file:$line $1"
-[ -n "$2" ]&&echo -e "$CC_WARN$message (update it)$CC_RESET" >&2||die "$message"
+[ -n "$2" ]&&printf "$CC_WARN%s$CC_RESET" "$message (update it)" >&2||die "$message"
 }
 _stacktrace(){
 local frame=1 line func src bestChoice
@@ -445,7 +445,7 @@ local sig="$2"
 local current new
 debug 3 "remove $remove from $sig"
 current="$(trap -p "$sig"|awk -F"'" '{print $2}')"
-new="$(echo "$current"|sed "s#;* *$remove##")"
+new="$(printf '%s' "$current"|sed "s#;* *$remove##")"
 trap "$new" "$sig"
 }
 mktemp(){
@@ -482,7 +482,7 @@ debug "create file $result"
 touch "$result"
 fi
 fi
-echo "$result"
+printf '%s' "$result"
 is empty -- "$ttl"||(_rm_temp "$ttl" "$result" >/dev/null 2>&1&
 disown)
 }
@@ -538,39 +538,40 @@ first(){
 local value
 for value in "$@";do
 if [[ $value ]];then
-echo "$value"
+printf '%s' "$value"
 return 0
 fi
 done
 return 1
 }
-CURSOR_UP=$'\033[A'
-CURSOR_DOWN=$'\033[B'
-CURSOR_RIGHT=$'\033[C'
-CURSOR_LEFT=$'\033[D'
-CURSOR_NEXT=$'\033[E'
-CURSOR_PREVIOUS=$'\033[F'
-CURSOR_POS1=$'\033[G'
-CURSOR_TOP=$'\033[H'
-CURSOR_STORE=$'\033[7'
-CURSOR_RESTORE=$'\033[8'
-CURSOR_SHOW=$'\033[?25h'
-CURSOR_HIDE=$'\033[?25l'
+CURSOR_UP=$'\e[A'
+CURSOR_DOWN=$'\e[B'
+CURSOR_RIGHT=$'\e[C'
+CURSOR_LEFT=$'\e[D'
+CURSOR_NEXT=$'\e[E'
+CURSOR_PREVIOUS=$'\e[F'
+CURSOR_POS1=$'\e[G'
+CURSOR_TOP=$'\e[H'
+CURSOR_STORE=$'\e[7'
+CURSOR_RESTORE=$'\e[8'
+CURSOR_SHOW=$'\e[?25h'
+CURSOR_HIDE=$'\e[?25l'
 cursor(){
 local num="${2:-1}" col="${3:-1}"
 is enum --name=direction --allow="up down right left row pos next previous" --die -- "$1"
 is integer --name=num --min=1 --die -- "$num"
-is integer --name=col --min=1 --die -- "$col"
 is integer --name=arguments --max=3 --die -- $#
 case "$1" in
-up)echo -n $'\033['$num'A';;
-down)echo -n $'\033['$num'B';;
-right)echo -n $'\033['$num'C';;
-left)echo -n $'\033['$num'D';;
-row)echo -n $'\033['$num'H';;
-pos)echo -n $'\033['"$num;$col"'H';;
-next)echo -n $'\033['$num'E';;
-previous)echo -n $'\033['$num'F'
+up)printf '\e[%sA' "$num";;
+down)printf '\e[%sB' "$num";;
+right)printf '\e[%sC' "$num";;
+left)printf '\e[%sD' "$num";;
+row)printf '\e[%sH' "$num";;
+pos)is integer --name=col --min=1 --die -- "$col"
+printf '\e[%s;%sH' "$num" "$col"
+;;
+next)printf '\e[%sE' "$num";;
+previous)printf '\e[%sF' "$num"
 esac
 }
 character(){
@@ -580,24 +581,24 @@ is integer --name=num --min=1 --die -- "$num"
 case "$1" in
 repeat)is set --name=character --min=1 --die -- "$3"
 is length --name=character --min=1 --max=1 --die -- "$3"
-((num==1))&&echo -n "$3"||echo -n "$3"$'\033['$((num-1))'b'
+((num==1))&&printf '%s' "$3"||printf '%s\e[%sb' "$3" $((num-1))
 ;;
-delete)echo -n $'\033['$num'P';;
-erase)echo -n $'\033['$num'X'
+delete)printf '\e[%sP' "$num";;
+erase)printf '\e[%sX' "$num"
 esac
 }
-SCROLL_UP=$'\033[M'
-CLEAR_SCREEN=$'\033[2J'
-CLEAR_UP=$'\033[1J'
-CLEAR_DOWN=$'\033[0J'
-CLEAR_EOL=$'\033[0K'
-CLEAR_SOL=$'\033[1K'
-CLEAR_LINE=$'\033[2K'
-SCREEN_RESTORE=$'\033[?47l'
-SCREEN_SAVE=$'\033[?47h'
+SCROLL_UP=$'\e[M'
+CLEAR_SCREEN=$'\e[2J'
+CLEAR_UP=$'\e[1J'
+CLEAR_DOWN=$'\e[0J'
+CLEAR_EOL=$'\e[0K'
+CLEAR_SOL=$'\e[1K'
+CLEAR_LINE=$'\e[2K'
+SCREEN_RESTORE=$'\e[?47l'
+SCREEN_SAVE=$'\e[?47h'
 erase_line(){
 _deprecated "Use $CLEAR_LINE" warn
-echo -n "$CLEAR_LINE"
+printf "$CLEAR_LINE"
 }
 debug(){
 local level=1 func text sign='>'
@@ -624,7 +625,7 @@ is integer --name=arguments --max=1 --die -- $#
 local text trap line func src
 text="$(input "$@")"
 [[ $text != *"Uncaught exception at"* ]]||trap=1
-echo -e "$CC_CRITICAL$text in ${FUNCNAME[1]}$CC_RESET" >&2
+printf "$CC_CRITICAL%s$CC_RESET\n" "$text in ${FUNCNAME[1]}" >&2
 _stacktrace "$trap"
 if command -v log >/dev/null;then
 log critical "$text"
@@ -644,14 +645,13 @@ is set --name=heading --die -- "$1"
 is set --name=usage --die -- "$2"
 heading "$(gettext Help): $1"
 info "Usage: $2"
-echo ""
+printf '\n'
 if is set -- "$3";then
 option_help "$3"
-echo ""
+printf '\n'
 fi
 if is set -- "$4";then
-echo "$4"
-echo
+printf '%s\n\n' "$4"
 fi
 exit 0
 }
@@ -664,56 +664,56 @@ critical(){
 local text
 text="$(input "$@")"
 is set -- "$text"||return 0
-printf "%s\n" "$CC_CRITICAL$text$CC_RESET"
+printf '%s\n' "$CC_CRITICAL$text$CC_RESET"
 ((${#_log_active[@]}==0))||log critical "$text"
 }
 error(){
 local text
 text="$(input "$@")"
 is set -- "$text"||return 0
-printf "%s\n" "$CC_ERROR$text$CC_RESET"
+printf '%s\n' "$CC_ERROR$text$CC_RESET"
 ((${#_log_active[@]}==0))||log error "$text"
 }
 warn(){
 local text
 text="$(input "$@")"
 is set -- "$text"||return 0
-printf "%s\n" "$CC_WARN$text$CC_RESET"
+printf '%s\n' "$CC_WARN$text$CC_RESET"
 ((${#_log_active[@]}==0))||log warn "$text"
 }
 notice(){
 local text
 text="$(input "$@")"
 is set -- "$text"||return 0
-printf "%s\n" "$CC_NOTICE$text$CC_RESET"
+printf '%s\n' "$CC_NOTICE$text$CC_RESET"
 ((${#_log_active[@]}==0))||log notice "$text"
 }
 info(){
 local text
 text="$(input "$@")"
 is set -- "$text"||return 0
-printf "%s\n" "$text"
+printf '%s\n' "$text"
 ((${#_log_active[@]}==0))||log info "$text"
 }
 ok(){
 local text
 text="$(input "$@")"
 is set -- "$text"||return 0
-echo -e "$CC_OK$text$CC_RESET"
+printf "$CC_OK%s$CC_RESET\n" "$text"
 ((${#_log_active[@]}==0))||log notice "$text"
 }
 invers(){
 local text
 text="$(input "$@")"
 is set -- "$text"||return 0
-echo -e "$CC_INVERS$text$CC_RESET"
+printf "$CC_INVERS%s$CC_RESET\n" "$text"
 ((${#_log_active[@]}==0))||log info "$text"
 }
 color(){
 local text
 text="$(input_args 1 "$@")"
 is set -- "$text"||return 0
-echo -e "$CC_ERROR$text$CC_RESET"
+printf "$CC_ERROR%s$CC_RESET\n" "$text"
 ((${#_log_active[@]}==0))||log info "$text"
 }
 uncolorize(){
@@ -743,7 +743,7 @@ esac
 local cols
 read -r _ cols < <(stty size)
 ((cols>60))||cols=60
-character repeat $cols "$char"
+printf '%s\n' "$(character repeat "$cols" "$char")"
 }
 _spinner_pid=""
 spinner_start(){
@@ -771,7 +771,7 @@ weather)spinner='🌤🌥🌦🌧🌨🌩🌪';;
 *)spinner='-\|/'
 esac
 local back=$((size+1))
-printf $CUR_HIDE
+printf "$CUR_HIDE"
 (while
 true
 do
@@ -791,32 +791,32 @@ kill "$_spinner_pid" >/dev/null 2>&1
 wait "$_spinner_pid" 2>/dev/null
 _spinner_pid=""
 printf "    \b\b\b\b"
-printf $CUR_SHOW
+printf "$CUR_SHOW"
 }
 logo(){
-a=$'\033[36m'
-b=$'\033[33m\033[1m'
-c=$'\033[43m\033[30m\033[1m'
-r=$'\033[0m'
-u=$'\033[4m'
-p="$(printf '%*s' $((($(tput cols)-80)/2)))"
-t="$(printf '%*s' $((($(tput cols)-${#1})/2)))"
-echo
-echo "$p$a                         $b  __   ____     ___"
-echo "$p$a           ######  ##### $b ▕  ▏ ▕    ╲   ▕   ▏ $a  ########### #####       #####"
-echo "$p$a          ######## ##### $b ▕  ▏ ▕     ╲  ▕   ▏ $a ############  #####     #####"
-echo "$p$a         ######### ##### $b ▕  ▏ ▕  ▕╲  ╲ ▕   ▏ $a #####          #####   #####"
-echo "$p$a        ########## ##### $b ▕  ▏ ▕  ▕ ╲  ╲▕   ▏ $a #####           ##### #####"
-echo "$p$a       ##### ##### ##### $b ▕  ▏ ▕  ▕  ╲  ▔   ▏ $a ############     #########"
-echo "$p$a      #####  ##### ##### $b ▕  ▏ ▕  ▕   ╲     ▏ $a ############     #########"
-echo "$p$a     #####   ##### ##### $b ▕  ▏ ▕  ▕    ╲    ▏ $a #####           ##### #####"
-echo "$p$a    #####    ##### ##### $b  ▔▔   ▔▔▔     ▔▔▔▔  $a #####          #####   #####"
-echo "$p$a   ##### ######### ########################### ############  #####     #####"
-echo "$p$a  ##### ##########  #########################   ########### #####       ##### $r"
-echo "$p$b▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄$r$c"
-echo "$t$1$r"
-echo "$p$b▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀$r"
-echo
+a=$'\e[36m'
+b=$'\e[33m\e[1m'
+c=$'\e[43m\e[30m\e[1m'
+r=$'\e[0m'
+u=$'\e[4m'
+p="$(character repeat $((($(tput cols)-80)/2)) ' ')"
+t="$(character repeat $((($(tput cols)-${#1})/2)) ' ')"
+printf '\n'
+printf "$p$a                         $b  __   ____     ___\n"
+printf "$p$a           ######  ##### $b ▕  ▏ ▕    ╲   ▕   ▏ $a  ########### #####       #####\n"
+printf "$p$a          ######## ##### $b ▕  ▏ ▕     ╲  ▕   ▏ $a ############  #####     #####\n"
+printf "$p$a         ######### ##### $b ▕  ▏ ▕  ▕╲  ╲ ▕   ▏ $a #####          #####   #####\n"
+printf "$p$a        ########## ##### $b ▕  ▏ ▕  ▕ ╲  ╲▕   ▏ $a #####           ##### #####\n"
+printf "$p$a       ##### ##### ##### $b ▕  ▏ ▕  ▕  ╲  ▔   ▏ $a ############     #########\n"
+printf "$p$a      #####  ##### ##### $b ▕  ▏ ▕  ▕   ╲     ▏ $a ############     #########\n"
+printf "$p$a     #####   ##### ##### $b ▕  ▏ ▕  ▕    ╲    ▏ $a #####           ##### #####\n"
+printf "$p$a    #####    ##### ##### $b  ▔▔   ▔▔▔     ▔▔▔▔  $a #####          #####   #####\n"
+printf "$p$a   ##### ######### ######""#####################"" ############  #####     #####\n"
+printf "$p$a  ##### ##########  #####""#################### ""  ########### #####       ##### $r\n"
+printf "$p$b▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄""▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄""▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄$r$c\n"
+printf "$t%s$r\n" "$1"
+printf "$p$b▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀""▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀""▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀$r\n"
+printf '\n'
 }
 check(){
 eval set -- "$(option_parse $'n name +\nd die -\ns sanitize -\n- min +\n- max +\n- allow +' "$@")"
@@ -990,7 +990,7 @@ fi
 ;;
 *)die "$(eval_gettext 'A check named ${check} is not defined')"
 esac
-echo "$res"
+printf '%s' "$res"
 }
 is(){
 check "$@" >/dev/null
@@ -1011,13 +1011,13 @@ trim_start(){
 is integer --name=arguments --max=2 --die -- $#
 local str="${1-}"
 local char="${2:-[:space:]}"
-echo "${str#"${str%%[!$char]*}"}"
+printf '%s' "${str#"${str%%[!$char]*}"}"
 }
 trim_end(){
 is integer --name=arguments --max=2 --die -- $#
 local str="${1:-}"
 local char="${2:-[:space:]}"
-echo "${str%"${str##*[!$char]}"}"
+printf '%s' "${str%"${str##*[!$char]}"}"
 }
 trim(){
 is integer --name=arguments --max=2 --die -- $#
@@ -1027,15 +1027,15 @@ to_alphanum(){
 is integer --name=arguments --max=1 --die -- $#
 local text
 text="$(input "$@")"
-echo "${text//[^a-zA-Z0-9_]/_}"
+printf '%s' "${text//[^a-zA-Z0-9_]/_}"
 }
 value_if_variable(){
 is integer --name=arguments --max=2 --die -- $#
 local _name="$1"
 if [[ $_name =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]&&[ -n "${!_name-}" ];then
-echo "${!_name}"
+printf '%s' "${!_name}"
 else
-echo "$_name"
+printf '%s' "$_name"
 fi
 }
 [[ $- =~ i ]]||set -eE
diff --git a/core/output b/core/output
--- a/core/output
+++ b/core/output
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC2034
 # shellcheck source=base
 source /dev/null
 
@@ -9,29 +10,29 @@ source /dev/null
 ######################################################################################
 
 # Cursor up 1 line
-CURSOR_UP=$'\033[A'
+CURSOR_UP=$'\e[A'
 #  Cursor down 1 line
-CURSOR_DOWN=$'\033[B'
+CURSOR_DOWN=$'\e[B'
 #  Cursor right 1 col
-CURSOR_RIGHT=$'\033[C'
+CURSOR_RIGHT=$'\e[C'
 # Cursor left 1 col
-CURSOR_LEFT=$'\033[D'
+CURSOR_LEFT=$'\e[D'
 # Next Line (down, col 1)
-CURSOR_NEXT=$'\033[E'
+CURSOR_NEXT=$'\e[E'
 # Previous Line (up, col 1)
-CURSOR_PREVIOUS=$'\033[F'
+CURSOR_PREVIOUS=$'\e[F'
 # Cursor to start of line
-CURSOR_POS1=$'\033[G'
+CURSOR_POS1=$'\e[G'
 # Cursor to top-left
-CURSOR_TOP=$'\033[H'
+CURSOR_TOP=$'\e[H'
 # Save cursor pos
-CURSOR_STORE=$'\033[7' # or \033[s
+CURSOR_STORE=$'\e[7' # or \e[s
 # Restore cursor pos
-CURSOR_RESTORE=$'\033[8' # or \033[u
+CURSOR_RESTORE=$'\e[8' # or \e[u
 # Show cursor
-CURSOR_SHOW=$'\033[?25h'
+CURSOR_SHOW=$'\e[?25h'
 # Hide cursor
-CURSOR_HIDE=$'\033[?25l'
+CURSOR_HIDE=$'\e[?25l'
 
 # Move cursor on console
 #
@@ -45,17 +46,19 @@ cursor() {
     local num="${2:-1}" col="${3:-1}"
     is enum --name=direction --allow="up down right left row pos next previous" --die -- "$1"
     is integer --name=num --min=1 --die -- "$num"
-    is integer --name=col --min=1 --die -- "$col"
     is integer --name=arguments --max=3 --die -- $#
     case "$1" in
-    up) echo -n $'\033['$num'A' ;;
-    down) echo -n $'\033['$num'B' ;;
-    right) echo -n $'\033['$num'C' ;;
-    left) echo -n $'\033['$num'D' ;;
-    row) echo -n $'\033['$num'H' ;;
-    pos) echo -n $'\033['"$num;$col"'H' ;;
-    next) echo -n $'\033['$num'E' ;;
-    previous) echo -n $'\033['$num'F' ;;
+    up) printf '\e[%sA' "$num" ;;
+    down) printf '\e[%sB' "$num" ;;
+    right) printf '\e[%sC' "$num" ;;
+    left) printf '\e[%sD' "$num" ;;
+    row) printf '\e[%sH' "$num" ;;
+    pos)
+        is integer --name=col --min=1 --die -- "$col"
+        printf '\e[%s;%sH' "$num" "$col"
+        ;;
+    next) printf '\e[%sE' "$num" ;;
+    previous) printf '\e[%sF' "$num" ;;
     esac
 }
 
@@ -72,33 +75,33 @@ character() {
     repeat)
         is set --name=character --min=1 --die -- "$3"
         is length --name=character --min=1 --max=1 --die -- "$3"
-        ((num == 1)) && echo -n "$3" || echo -n "$3"$'\033['$((num - 1))'b'
+        ((num == 1)) && printf '%s' "$3" || printf '%s\e[%sb' "$3" $((num - 1))
         ;;
-    delete) echo -n $'\033['$num'P' ;;
-    erase) echo -n $'\033['$num'X' ;;
+    delete) printf '\e[%sP' "$num" ;;
+    erase) printf '\e[%sX' "$num" ;;
     esac
 }
 
 # Reverse Index (up, scroll)
-SCROLL_UP=$'\033[M'
+SCROLL_UP=$'\e[M'
 
 # Clear entire screen
-CLEAR_SCREEN=$'\033[2J'
+CLEAR_SCREEN=$'\e[2J'
 # Clear from start of screen to cursor
-CLEAR_UP=$'\033[1J'
+CLEAR_UP=$'\e[1J'
 # Clear from cursor to end of screen
-CLEAR_DOWN=$'\033[0J'
+CLEAR_DOWN=$'\e[0J'
 # Clear from cursor to end of line
-CLEAR_EOL=$'\033[0K'
+CLEAR_EOL=$'\e[0K'
 # Clear from start of line to cursor
-CLEAR_SOL=$'\033[1K'
+CLEAR_SOL=$'\e[1K'
 # Clear entire line
-CLEAR_LINE=$'\033[2K'
+CLEAR_LINE=$'\e[2K'
 
 # restore screen
-SCREEN_RESTORE=$'\033[?47l'
+SCREEN_RESTORE=$'\e[?47l'
 # save screen
-SCREEN_SAVE=$'\033[?47h'
+SCREEN_SAVE=$'\e[?47h'
 
 # Deprecated: Remove current line
 # Use $CLEAR_LINE
@@ -108,7 +111,8 @@ SCREEN_SAVE=$'\033[?47h'
 # Usage:    erase_line
 erase_line() {
     _deprecated "Use $CLEAR_LINE" warn
-    echo -n "$CLEAR_LINE"
+    # shellcheck disable=SC2059
+    printf "$CLEAR_LINE"
 }
 
 ######################################################################################
@@ -180,7 +184,7 @@ die() {
     text="$(input "$@")"
     [[ "$text" != *"Uncaught exception at"* ]] || trap=1
     # output
-    echo -e "${CC_CRITICAL}$text in ${FUNCNAME[1]}${CC_RESET}" >&2
+    printf "${CC_CRITICAL}%s${CC_RESET}\n" "$text in ${FUNCNAME[1]}" >&2
     _stacktrace "$trap"
     if command -v log >/dev/null; then
         log critical "$text"
@@ -210,14 +214,13 @@ help() {
     # processing
     heading "$(gettext Help): $1"
     info "Usage: $2"
-    echo ""
+    printf '\n'
     if is set -- "$3"; then
         option_help "$3"
-        echo ""
+        printf '\n'
     fi
     if is set -- "$4"; then
-        echo "$4"
-        echo
+        printf '%s\n\n' "$4"
     fi
     exit 0
 }
@@ -248,7 +251,7 @@ critical() {
     local text
     text="$(input "$@")"
     is set -- "$text" || return 0
-    printf "%s\n" "${CC_CRITICAL}$text${CC_RESET}"
+    printf '%s\n' "${CC_CRITICAL}$text${CC_RESET}"
     ((${#_log_active[@]} == 0)) || log critical "$text"
 }
 
@@ -261,7 +264,7 @@ error() {
     local text
     text="$(input "$@")"
     is set -- "$text" || return 0
-    printf "%s\n" "${CC_ERROR}$text${CC_RESET}"
+    printf '%s\n' "${CC_ERROR}$text${CC_RESET}"
     ((${#_log_active[@]} == 0)) || log error "$text"
 }
 
@@ -275,7 +278,7 @@ warn() {
     local text
     text="$(input "$@")"
     is set -- "$text" || return 0
-    printf "%s\n" "${CC_WARN}$text${CC_RESET}"
+    printf '%s\n' "${CC_WARN}$text${CC_RESET}"
     ((${#_log_active[@]} == 0)) || log warn "$text"
 }
 
@@ -289,7 +292,7 @@ notice() {
     local text
     text="$(input "$@")"
     is set -- "$text" || return 0
-    printf "%s\n" "${CC_NOTICE}$text${CC_RESET}"
+    printf '%s\n' "${CC_NOTICE}$text${CC_RESET}"
     ((${#_log_active[@]} == 0)) || log notice "$text"
 }
 
@@ -302,7 +305,7 @@ info() {
     local text
     text="$(input "$@")"
     is set -- "$text" || return 0
-    printf "%s\n" "$text"
+    printf '%s\n' "$text"
     ((${#_log_active[@]} == 0)) || log info "$text"
 }
 
@@ -315,7 +318,7 @@ ok() {
     local text
     text="$(input "$@")"
     is set -- "$text" || return 0
-    echo -e "${CC_OK}$text${CC_RESET}"
+    printf "${CC_OK}%s${CC_RESET}\n" "$text"
     ((${#_log_active[@]} == 0)) || log notice "$text"
 }
 
@@ -328,7 +331,7 @@ invers() {
     local text
     text="$(input "$@")"
     is set -- "$text" || return 0
-    echo -e "${CC_INVERS}$text${CC_RESET}"
+    printf "${CC_INVERS}%s${CC_RESET}\n" "$text"
     ((${#_log_active[@]} == 0)) || log info "$text"
 }
 
@@ -341,7 +344,7 @@ color() {
     local text
     text="$(input_args 1 "$@")"
     is set -- "$text" || return 0
-    echo -e "${CC_ERROR}$text${CC_RESET}"
+    printf "${CC_ERROR}%s${CC_RESET}\n" "$text"
     ((${#_log_active[@]} == 0)) || log info "$text"
 }
 
@@ -423,7 +426,7 @@ horizontal_line() {
     local cols
     read -r _ cols < <(stty size)
     ((cols > 60)) || cols=60
-    character repeat $cols "$char"
+    printf '%s\n' "$(character repeat "$cols" "$char")"
 }
 
 _spinner_pid=""
@@ -478,7 +481,8 @@ spinner_start() {
     esac
     local back=$((size + 1))
     # Spinner function running in background loop
-    printf $CUR_HIDE # make cursor invisible
+    # shellcheck disable=SC2059
+    printf "$CUR_HIDE" # make cursor invisible
     (
         while true; do
             for ((i = 0; i < ${#spinner}; i += chars)); do
@@ -504,37 +508,39 @@ spinner_stop() {
     wait "$_spinner_pid" 2>/dev/null
     _spinner_pid=""
     printf "    \b\b\b\b" # Clear spinner character
-    printf $CUR_SHOW      # make cursor visible again
+    # shellcheck disable=SC2059
+    printf "$CUR_SHOW" # make cursor visible again
 }
 
 # Output Logo with title text
 #
-# You may overwrite this function with one displaying your own logo by loading it from your `extra/mycompany-logo` or so.
+# You may overwrite this function with one displaying your own logo by loading it from your `extra/my-company-logo` or so.
 #
 # Usage:    logo <text>
 # Output:   ASCII art logo including title
+# shellcheck disable=SC2059
 logo() {
-    a=$'\033[36m'                # cyan
-    b=$'\033[33m\033[1m'         # yellow bold
-    c=$'\033[43m\033[30m\033[1m' # yellow bg + black bold
-    r=$'\033[0m'                 # reset
-    u=$'\033[4m'                 # underline
-    p="$(printf '%*s' $((($(tput cols) - 80) / 2)))"
-    t="$(printf '%*s' $((($(tput cols) - ${#1}) / 2)))"
-    echo
-    echo "$p$a                         $b  __   ____     ___"
-    echo "$p$a           ######  ##### $b ▕  ▏ ▕    ╲   ▕   ▏ $a  ########### #####       #####"
-    echo "$p$a          ######## ##### $b ▕  ▏ ▕     ╲  ▕   ▏ $a ############  #####     #####"
-    echo "$p$a         ######### ##### $b ▕  ▏ ▕  ▕╲  ╲ ▕   ▏ $a #####          #####   #####"
-    echo "$p$a        ########## ##### $b ▕  ▏ ▕  ▕ ╲  ╲▕   ▏ $a #####           ##### #####"
-    echo "$p$a       ##### ##### ##### $b ▕  ▏ ▕  ▕  ╲  ▔   ▏ $a ############     #########"
-    echo "$p$a      #####  ##### ##### $b ▕  ▏ ▕  ▕   ╲     ▏ $a ############     #########"
-    echo "$p$a     #####   ##### ##### $b ▕  ▏ ▕  ▕    ╲    ▏ $a #####           ##### #####"
-    echo "$p$a    #####    ##### ##### $b  ▔▔   ▔▔▔     ▔▔▔▔  $a #####          #####   #####"
-    echo "$p$a   ##### ######### ########################### ############  #####     #####"
-    echo "$p$a  ##### ##########  #########################   ########### #####       ##### $r"
-    echo "$p$b▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄$r$c"
-    echo "$t$1$r"
-    echo "$p$b▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀$r"
-    echo
+    a=$'\e[36m'            # cyan
+    b=$'\e[33m\e[1m'       # yellow bold
+    c=$'\e[43m\e[30m\e[1m' # yellow bg + black bold
+    r=$'\e[0m'             # reset
+    u=$'\e[4m'             # underline
+    p="$(character repeat $((($(tput cols) - 80) / 2)) ' ')"
+    t="$(character repeat $((($(tput cols) - ${#1}) / 2)) ' ')"
+    printf '\n'
+    printf "$p$a                         $b  __   ____     ___\n"
+    printf "$p$a           ######  ##### $b ▕  ▏ ▕    ╲   ▕   ▏ $a  ########### #####       #####\n"
+    printf "$p$a          ######## ##### $b ▕  ▏ ▕     ╲  ▕   ▏ $a ############  #####     #####\n"
+    printf "$p$a         ######### ##### $b ▕  ▏ ▕  ▕╲  ╲ ▕   ▏ $a #####          #####   #####\n"
+    printf "$p$a        ########## ##### $b ▕  ▏ ▕  ▕ ╲  ╲▕   ▏ $a #####           ##### #####\n"
+    printf "$p$a       ##### ##### ##### $b ▕  ▏ ▕  ▕  ╲  ▔   ▏ $a ############     #########\n"
+    printf "$p$a      #####  ##### ##### $b ▕  ▏ ▕  ▕   ╲     ▏ $a ############     #########\n"
+    printf "$p$a     #####   ##### ##### $b ▕  ▏ ▕  ▕    ╲    ▏ $a #####           ##### #####\n"
+    printf "$p$a    #####    ##### ##### $b  ▔▔   ▔▔▔     ▔▔▔▔  $a #####          #####   #####\n"
+    printf "$p$a   ##### ######### ######""#####################"" ############  #####     #####\n"
+    printf "$p$a  ##### ##########  #####""#################### ""  ########### #####       ##### $r\n"
+    printf "$p$b▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄""▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄""▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄$r$c\n"
+    printf "$t%s$r\n" "$1"
+    printf "$p$b▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀""▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀""▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀$r\n"
+    printf '\n'
 }
