allow to set host by option in mongo

diff --git a/base b/base
--- a/base
+++ b/base
@@ -522,14 +522,19 @@ res=$(command curl -s -w "%{url_effective} with RC:%{http_code}" $opt -L "$@"|ta
 debug "Response: $res"
 CURL_HTTP_CODE=${res: -3}
 [ -z "$store" ]||variables store "$store" CURL_HTTP_CODE
+if [[ ! $CURL_HTTP_CODE =~ ^2[0-9]{2}$ ]];then
+error "Error: $res" >&2
+if [ -e "$file" ];then
+local val
+val="$(cat "$file")"
+[[ $val =~ ^\{ ]]&&jq . <<<"$val"|warn >&2||warn "$val" >&2
+fi
+fi
 if [ -n "$file" ];then
 cat "$file"
 rm "$file"
 fi
-if [[ ! $CURL_HTTP_CODE =~ ^2[0-9]{2}$ ]];then
-error "Error: $res" >&2
-return 1
-fi
+[[ $CURL_HTTP_CODE =~ ^2[0-9]{2}$ ]]
 }
 first(){
 local value
@@ -984,7 +989,6 @@ else
 echo "$_name"
 fi
 }
-echo "${!1}"
 [[ $- =~ i ]]||set -eE
 set -o pipefail
 is set -- "${BASH_VERSION:-}"||die "No bash CLI! This can only be run under bash"
diff --git a/full b/full
--- a/full
+++ b/full
@@ -522,14 +522,19 @@ res=$(command curl -s -w "%{url_effective} with RC:%{http_code}" $opt -L "$@"|ta
 debug "Response: $res"
 CURL_HTTP_CODE=${res: -3}
 [ -z "$store" ]||variables store "$store" CURL_HTTP_CODE
+if [[ ! $CURL_HTTP_CODE =~ ^2[0-9]{2}$ ]];then
+error "Error: $res" >&2
+if [ -e "$file" ];then
+local val
+val="$(cat "$file")"
+[[ $val =~ ^\{ ]]&&jq . <<<"$val"|warn >&2||warn "$val" >&2
+fi
+fi
 if [ -n "$file" ];then
 cat "$file"
 rm "$file"
 fi
-if [[ ! $CURL_HTTP_CODE =~ ^2[0-9]{2}$ ]];then
-error "Error: $res" >&2
-return 1
-fi
+[[ $CURL_HTTP_CODE =~ ^2[0-9]{2}$ ]]
 }
 first(){
 local value
@@ -984,7 +989,6 @@ else
 echo "$_name"
 fi
 }
-echo "${!1}"
 [[ $- =~ i ]]||set -eE
 set -o pipefail
 is set -- "${BASH_VERSION:-}"||die "No bash CLI! This can only be run under bash"
@@ -1001,7 +1005,7 @@ jira(){
 is set --name=JIRA_HOST --die -- "$JIRA_HOST"
 is set --name=ATLASSIAN_USER --die -- "$ATLASSIAN_USER"
 is set --name=ATLASSIAN_TOKEN --die -- "$ATLASSIAN_TOKEN"
-is enum --name=command --allow="get search create update delete project fields json adf" --die -- "$1"&&local command="$1"&&shift
+is enum --name=command --allow="get search create update delete project fields json adf_to_md md_to_adf" --die -- "$1"&&local command="$1"&&shift
 case "$command" in
 get)is set --name=arguments --max=1 --die -- $#
 is set --name=issueId-or-key --die -- "$1"
@@ -1017,7 +1021,7 @@ _jira GET "search/jql?jql=$(urlencode "$1")"|jq .issues[].id -r
 create)is set --name=arguments --max=1 --die -- $#
 is set --name=json --die -- "$1"
 debug "CREATE issue ${jq-r '.fields.summary' <<<"$1"}"
-_jira POST issue "$1"|jq .id
+_jira POST issue "$1"|jq .id -r
 ;;
 update)is set --name=arguments --max=1 --die -- $#
 is set --name=json --die -- "$1"
@@ -1040,19 +1044,37 @@ is set --name=issueTypeId --die -- "$2"
 debug "GET fields $1/$2"
 _jira GET "issue/createmeta/$1/issuetypes/$2"
 ;;
-json)local empty='{"fields":{}}'
-local json="${1:-$empty}"&&shift
+json)local empty='{"fields":{}}' var="$1"
+local json="${!1:-$empty}"&&shift
 is enum --name=sub-command --allow="set get remove" --die -- "$1"&&local subCommand="$1"&&shift
 is set --name=field --die -- "$1"&&local field="$1"
 case "$subCommand" in
-set)jq --arg v "$2" ".fields.$field = \$v" <<<"$json";;
-get)jq ".fields.$field" <<<"$json";;
-remove)jq "del(.fields.$field)" <<<"$json"
+set)if
+[ -z "$2" ]||[[ $2 =~ ^adf$|^json$ && -z $3 ]]
+then
+jira json $var remove $field
+elif [ "$2" = "json" ]&&[ -n "$3" ];then
+printf -v "$var" '%s' "$(jq --argjson v "$3" ".fields.$field = \$v" <<<"$json")"
+elif [ "$2" = "adf" ]&&[ -n "$3" ];then
+local val
+[[ $3 =~ ^\{ ]]&&val="$3"||val="$(jira md_to_adf "$3")"
+debug "in:  $3"
+debug "adf: $val"
+printf -v "$var" '%s' "$(jq --argjson v "$val" ".fields.$field = \$v" <<<"$json")"
+elif is integer -- "$2";then
+printf -v "$var" '%s' "$(jq ".fields.$field = $2" <<<"$json")"
+else
+printf -v "$var" '%s' "$(jq --arg v "$2" ".fields.$field = \$v" <<<"$json")"
+fi
+;;
+get)local val
+val="$(jq ".fields.$field" <<<"$json")"
+[[ $2 == "md" && $val =~ ^\{ ]]&&jira adf_to_md "$val"||echo "$val"
+;;
+remove)printf -v "$var" '%s' "$(jq "del(.fields.$field)" <<<"$json")"
 esac
 ;;
-adf)is enum --name=sub-command --allow="parse format" --die -- "$1"&&local subCommand="$1"&&shift
-case "$subCommand" in
-parse)is set --name=json --die -- "$1"&&local json="$1"
+adf_to_md)is set --name=json --die -- "$1"&&local json="$1"
 jq -r '
     def para(p):
       p.content[]?.text // "";
@@ -1088,8 +1110,8 @@ jq -r '
     s/<code>(.+?)<\/code>/`\1`/g
   '
 ;;
-format)is set --name=text --die -- "$1"
-jq -n --arg text "$text" '
+md_to_adf)is set --name=text --die -- "$1"
+jq -n --arg text "$1" '
     def paragraph(t):
       { type: "paragraph", content: [{ type: "text", text: t }] };
 
@@ -1197,7 +1219,6 @@ jq -n --arg text "$text" '
     s/`([^`]+)`/<code>\1<\/code>/g
   '
 esac
-esac
 }
 _jira(){
 local METHOD=$1
@@ -1224,13 +1245,23 @@ done
 }
 use module/software
 mongo(){
+local host="$server"
+eval set -- "$(option_parse $'h host +' "$@")"
+while true;do
+case "$1" in
+-h|--host)host="$2"&&shift 2;;
+--)shift&&break;;
+*)die "$(gettext "Unrecognized option"): $1"
+esac
+done
+debug "$*"
 is integer --name=arguments --max=2 --die -- $#
 is set --name=command --die -- "$2"
 local cluster key
 install mongosh
-cluster="$(sed 's/^[^.]*\.//' <<<"$server")"
+cluster="$(sed 's/^[^.]*\.//' <<<"$host")"
 debug "Use settings for $cluster"
-command mongosh "mongodb://$(hash MONGO_ADMIN_USERPASS get "$cluster")@$server:27017/$1" \
+command mongosh "mongodb://$(hash MONGO_ADMIN_USERPASS get "$cluster")@$host:27017/$1" \
 --eval "print(EJSON.stringify($2))"
 }
 postgres(){
@@ -3478,16 +3509,37 @@ fixed="$(jq .FixedVersion -r <<<"$json")"
 [ "$fixed" != "null" ]||fixed="-"
 fixStatus="$(jq .Status -r <<<"$json")"
 [ "$fixStatus" != "null" ]||fixStatus="-"
-+ jira json fields set project "${_trivy_jira[board]}"
-jira json fields set priority "$priority"
+links="$(jq '.References[]?' -r <<<"$json"|sed 's/^/- /')"
+echo "$fields"
+debug "-------------------------------------"
+jira json fields set project json "{\"id\":${_trivy_jira[board]}}"
+jira json fields set issuetype json "{\"id\":${_trivy_jira[issueType]}}"
+echo "$fields"
+debug "-------------------------------------"
+jira json fields set priority json "{\"name\":\"$priority\"}"
+echo "$fields"
+debug "-------------------------------------"
 jira json fields set summary "$id"
-jira json fields set description "$(jira adf format "$title"$'\n\n'"$description")"
-jira json fields set issuetype "{\"id\": \"${_trivy_jira[issueType]}\"}"
-jira json fields set ${_trivy_jira[field_sources]} "$(jira adf format "$source $target ($type)")"
-jira json fields set ${_trivy_jira[field_rating]} "$(jira adf format "$severity (CVSS Rating $cvss)")"
-jira json fields set ${_trivy_jira[field_version]} "$(jira adf format "Installiert ist Version $installed gefixt ab Version $fixed $fixStatus")"
-jira json fields set ${_trivy_jira[field_links]} "$(jira adf format "$links")"
-jira json fields set labels "[\"cve\", \"$(sed 's#.*ekz.de/##;s#/-/.*##;s#[/.]#", "#g' <<<"$source")\"]"
+echo "$fields"
+debug "-------------------------------------"
+jira json fields set description adf "$title"$'\n\n'"$description"
+echo "$fields"
+debug "-------------------------------------"
+jira json fields set ${_trivy_jira[field_sources]} adf "$(date +%Y-%m) > $source $target ($type)"
+echo "$fields"
+debug "-------------------------------------"
+jira json fields set ${_trivy_jira[field_rating]} adf "$severity (CVSS Rating ${cvss:--})"
+echo "$fields"
+debug "-------------------------------------"
+jira json fields set ${_trivy_jira[field_version]} adf "Installiert ist Version $installed gefixt ab Version $fixed $fixStatus"
+echo "$fields"
+debug "-------------------------------------"
+jira json fields set ${_trivy_jira[field_links]} adf "$links"
+echo "$fields"
+debug "-------------------------------------"
+jira json fields set labels json "[\"cve\", \"$(sed 's#.*ekz.de/##;s#/-/.*##;s#[/.]#", "#g' <<<"$source")\"]"
+echo "$fields"
+debug "-------------------------------------"
 issue="$(jira create "$fields")"
 created=1
 fi
@@ -3505,7 +3557,7 @@ fi
 fi
 if is set -- "$created";then
 local sources new update addLabel=()
-sources="$(jira fields get "${_trivy_jira[field_sources]}")"
+sources="$(jira fields "${_trivy_jira[field_sources]}")"
 [ "$sources" = "null" ]&&sources=""||sources="$(jira adf parse "$sources")"
 if is set -- "$sources";then
 new="$(echo -e "$sources\n$(date +%Y-%m) > $source $target ($type)"|sed -n '/>/p'|sort -t'>' -r -k2,1|sort -t'>' -u -r -k2)"
