is --output as replacement for check

diff --git a/base b/base
--- a/base
+++ b/base
@@ -819,11 +819,17 @@ printf "$p$b▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀�
 printf '\n'
 }
 check(){
-eval set -- "$(option_parse $'n name +\nd die -\ns sanitize -\n- min +\n- max +\n- allow +' "$@")"
-local name die sanitize min max allow
+_deprecated "Use is ... --output" warn
+is --output "$@"
+}
+is(){
+eval set -- "$(option_parse $'n name +\nd die -\ns sanitize -\n- min +\n- max +\n- allow +\no output -\nm message +' "$@")"
+local name die sanitize min max allow message output
 while true;do
 case "$1" in
 -n|--name)name="$2"&&shift 2;;
+-m|--message)message="; $2"&&shift 2;;
+-o|--output)output=1&&shift;;
 -d|--die)die=1&&shift;;
 -s|--sanitize)sanitize=1&&shift;;
 --min)[[ $2 =~ ^[-+]?[0-9]+([.][0-9]+)?$ ]]&&min="$2"&&shift 2||die "$(printf "$(gettext "Parameter %s needs number")" min)";;
@@ -842,13 +848,13 @@ case $check in
 set)if
 [ -z "$val" ]
 then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be set with a value')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be set with a value')$message"
 fi
 ;;
 empty)if
 [ -n "$val" ]
 then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be empty but has »${val}«')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be empty but has »${val}«')$message"
 fi
 ;;
 bool)if
@@ -858,7 +864,7 @@ res=1
 elif [[ -z $val || ${val,,} =~ ^(false|f|0|no|n|nein)$ ]];then
 res=0
 else
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The value »${val}« for "$name" could not be read as true or false')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The value »${val}« for "$name" could not be read as true or false')$message"
 fi
 ;;
 true)if
@@ -866,7 +872,7 @@ true)if
 then
 res=1
 else
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The value »${val}« for "$name" should be true but was »${val}«')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The value »${val}« for "$name" should be true but was »${val}«')$message"
 fi
 ;;
 false)if
@@ -874,7 +880,7 @@ false)if
 then
 res=0
 else
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The value »${val}« for "$name" should be false but was »${val}«')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The value »${val}« for "$name" should be false but was »${val}«')$message"
 fi
 ;;
 integer)if
@@ -883,23 +889,23 @@ then
 [[ $val =~ ^(-?[0-9]+) ]]&&res="${BASH_REMATCH[1]}"||true
 fi
 if [[ ! $res =~ ^-?[0-9]+$ ]];then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be an integer but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be an integer but »${val}« was given')$message"
 fi
 if [[ -n $min ]]&&[[ $min == "$max" ]];then
 if ((res!=min));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')$message"
 fi
 elif [[ -n $min && -n $max ]];then
 if ((res<min||res>max));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')$message"
 fi
 elif [[ -n $min ]];then
 if ((res<min));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')$message"
 fi
 elif [[ -n $max ]];then
 if ((res>max));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')$message"
 fi
 fi
 ;;
@@ -909,97 +915,94 @@ then
 [[ $val =~ ^(-?[0-9]+([.][0-9]+)?) ]]&&res="${BASH_REMATCH[1]}"||true
 fi
 if [[ ! $res =~ ^-?[0-9]+([.][0-9]+)?$ ]];then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be a float but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be a float but »${val}« was given')$message"
 fi
 if [[ -n $min ]]&&[[ $min == "$max" ]];then
 if ((res!=min));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')$message"
 fi
 elif [[ -n $min && -n $max ]];then
 if ((res<min||res>max));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')$message"
 fi
 elif [[ -n $min ]];then
 if ((res<min));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')$message"
 fi
 elif [[ -n $max ]];then
 if ((res>max));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')$message"
 fi
 fi
 ;;
 length)val=${#val}
 if [[ -n $min ]]&&[[ $min == "$max" ]];then
 if ((val!=min));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be exactly $min but »${res}« is $val characters long')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be exactly $min but »${res}« is $val characters long')$message"
 fi
 elif [[ -n $min && -n $max ]];then
 if ((val<min||val>max));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be between $min and $max but »${res}« is $val characters long')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be between $min and $max but »${res}« is $val characters long')$message"
 fi
 elif [[ -n $min ]];then
 if ((val<min));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be at least $min but »${res}« is $val characters long')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be at least $min but »${res}« is $val characters long')$message"
 fi
 elif [[ -n $max ]];then
 if ((val>max));then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be not more than $max but »${res}« is $val characters long')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The length of "$name" has to be not more than $max but »${res}« is $val characters long')$message"
 fi
 fi
 ;;
-enum)[ -n "$allow" ]||die "$(gettext "A list with --allow=<words> is needed for enum check")"
+enum)[ -n "$allow" ]||die "$(gettext "A list with --allow=<words> is needed for enum check")$message"
 if [[ " $allow " != *" $val "* ]];then
-[ -z "$die" ]&&return 1||die "$(eval_gettext '"$name" is set to "${val}" but has to be one of: $allow')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext '"$name" is set to "${val}" but has to be one of: $allow')$message"
 fi
 ;;
 date)if
 ! res=$(date_format unix "$val")
 then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be a parsable date format but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be a parsable date format but »${val}« was given')$message"
 fi
 ;;
 duration)[[ $res =~ ^-?[0-9] ]]&&res="$(duration_format seconds "$val")"||true
 if [[ ! $res =~ ^-?[0-9]+$ ]];then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be an integer or human duration but »${val}« was given')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" has to be an integer or human duration but »${val}« was given')$message"
 fi
 ;;
 path)if
 [ ! -e "$val" ]
 then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be an existing path')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be an existing path')$message"
 fi
 ;;
 file)if
 [ ! -f "$val" ]
 then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be an existing file')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be an existing file')$message"
 fi
 ;;
 directory)if
 [ ! -d "$val" ]
 then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be an existing directory')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be an existing directory')$message"
 fi
 ;;
 readable)if
 [ ! -r "$val" ]
 then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be a file readable for user')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be a file readable for user')$message"
 fi
 ;;
 writable)if
 [ ! -w "$val" ]
 then
-[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be a file writable for user')"
+[ -z "$die" ]&&return 1||die "$(eval_gettext 'The "$name" ${val} has to be a file writable for user')$message"
 fi
 ;;
 *)die "$(eval_gettext 'A check named ${check} is not defined')"
 esac
-printf '%s' "$res"
-}
-is(){
-check "$@" >/dev/null
+[ -z "$output" ]||printf '%s' "$res"
 }
 num_parameters(){
 _deprecated "Use: is integer $# --min=<val> --max=<val>"
diff --git a/core/validator b/core/validator
--- a/core/validator
+++ b/core/validator
@@ -6,7 +6,8 @@
 ### General Validation
 ######################################################################################
 
-# Validate and sanitize values.
+# Deprecated:Validate and sanitize values.
+# Use is ... --output
 #
 # This validation is possible using the `check` and @is function.
 # - `check` should be used for sanitize because it will output the value
@@ -56,14 +57,69 @@
 #
 #           - `if check integer age --min=18 -- "$1" >/dev/null; then`
 check() {
+    _deprecated "Use is ... --output" warn
+    is --output "$@"
+}
+
+# Validate and sanitize values.
+#
+# This validation is possible using the `check` and @is function.
+# - `check` should be used for sanitize because it will output the value
+# - @is should be used for checking only validity or stop processing on problem because no value is output
+#
+# Every parameter should be checked to prevent failure later in the code.
+# For such checks you run it with the `--die` option to stop processing if wrong.
+# But you can also use it in the program flow without that and use it's return status to check if it 0=ok or 1=failed.
+#
+# Because the values may start with an dash you should always put it at the end after '--' to prevent parsing it as option.
+#
+# The following checks are implemented:
+#
+# - `set` will fail if no value given
+# - `empty` will fail if not empty like ""
+# - `bool` will transform the value to `1` or `0` and allows: true/false, t/f, 1/0, yes/no, y/j/n, ja/nein, ""
+# - `true` should be a boolean true
+# - `false` should be a boolean false
+# - `integer` will check for a number maybe within a range
+# - `float` will check for a number maybe within a range
+# - `enum' will check against valid words using `--allow="word1 word2"`
+# - `length` check that the length is within range (like integer)
+# - `date` check that the input is parsable as date and return unix timestamp
+# - `duration` check and parse the @duration_format
+# - `path` check that value is an existing path (any type)
+# - `file` check that value is an existing file
+# - `directory` check that value is an existing directory
+# - `readable` check that value is a file readable by user
+# - `writable` check that value is a file writable by user
+#
+# Usage:    is <check> [options] -- <value>
+# Options:  d, die              # used in @is to stop with error instead of return state
+#           o, output           # will output the sanitized value
+#           n, name=<string>    # used in @is to display variable name in `die` message
+#           m, message=<string> # additional message like usage
+#           s, sanitize         # for integer
+#           min=<num>           # for integer
+#           max=<num>           # for integer
+#           allow=<words>       # for enum (space separated)
+# Output:   <value>             # may be sanitized
+# Exit:     with message if incorrect value
+# Example:  Check arguments:
+#
+#           - `is integer --name=arguments --max=2 -- $# >/dev/null` # mostly only check max, if all args are checked separately
+#           - `name="$(is integer --name=age --sanitize --min=0 --output -- "$1")"`
+#           - `init="$(is bool --name=init --output -- "$1")"`
+#           - `if is integer age --min=18 -- "$1"; then`
+is() {
     # parameter parsing
-    eval set -- "$(option_parse $'n name +\nd die -\ns sanitize -\n- min +\n- max +\n- allow +' "$@")"
-    local name die sanitize min max allow
+    eval set -- "$(option_parse $'n name +\nd die -\ns sanitize -\n- min +\n- max +\n- allow +\no output -\nm message +' "$@")"
+    local name die sanitize min max allow message output
     # shellcheck disable=SC2015
     # shellcheck disable=SC2059
     while true; do
         case "$1" in
         -n | --name) name="$2" && shift 2 ;;
+        -m | --message) message="; $2" && shift 2 ;;
+        -o | --output) output=1 && shift ;;
         -d | --die) die=1 && shift ;;
         -s | --sanitize) sanitize=1 && shift ;;
         --min) [[ "$2" =~ ^[-+]?[0-9]+([.][0-9]+)?$ ]] && min="$2" && shift 2 || die "$(printf "$(gettext "Parameter %s needs number")" min)" ;;
@@ -84,12 +140,12 @@ check() {
     case $check in
     set)
         if [ -z "$val" ]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be set with a value')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be set with a value')${message}"
         fi
         ;;
     empty)
         if [ -n "$val" ]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be empty but has »${val}«')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be empty but has »${val}«')${message}"
         fi
         ;;
     bool)
@@ -98,21 +154,21 @@ check() {
         elif [[ -z "$val" || "${val,,}" =~ ^(false|f|0|no|n|nein)$ ]]; then
             res=0
         else
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The value »${val}« for "$name" could not be read as true or false')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The value »${val}« for "$name" could not be read as true or false')${message}"
         fi
         ;;
     true)
         if [[ "${val,,}" =~ ^(true|t|1|yes|y|ja|j)$ ]]; then
             res=1
         else
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The value »${val}« for "$name" should be true but was »${val}«')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The value »${val}« for "$name" should be true but was »${val}«')${message}"
         fi
         ;;
     false)
         if [[ -z "$val" || "${val,,}" =~ ^(false|f|0|no|n|nein)$ ]]; then
             res=0
         else
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The value »${val}« for "$name" should be false but was »${val}«')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The value »${val}« for "$name" should be false but was »${val}«')${message}"
         fi
         ;;
     integer)
@@ -120,23 +176,23 @@ check() {
             [[ "$val" =~ ^(-?[0-9]+) ]] && res="${BASH_REMATCH[1]}" || true
         fi
         if [[ ! "$res" =~ ^-?[0-9]+$ ]]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be an integer but »${val}« was given')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be an integer but »${val}« was given')${message}"
         fi
         if [[ -n "$min" ]] && [[ "$min" == "$max" ]]; then
             if ((res != min)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')${message}"
             fi
         elif [[ -n "$min" && -n "$max" ]]; then
             if ((res < min || res > max)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')${message}"
             fi
         elif [[ -n "$min" ]]; then
             if ((res < min)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')${message}"
             fi
         elif [[ -n "$max" ]]; then
             if ((res > max)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')${message}"
             fi
         fi
         ;;
@@ -145,23 +201,23 @@ check() {
             [[ "$val" =~ ^(-?[0-9]+([.][0-9]+)?) ]] && res="${BASH_REMATCH[1]}" || true
         fi
         if [[ ! "$res" =~ ^-?[0-9]+([.][0-9]+)?$ ]]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be a float but »${val}« was given')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be a float but »${val}« was given')${message}"
         fi
         if [[ -n "$min" ]] && [[ "$min" == "$max" ]]; then
             if ((res != min)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')${message}"
             fi
         elif [[ -n "$min" && -n "$max" ]]; then
             if ((res < min || res > max)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')${message}"
             fi
         elif [[ -n "$min" ]]; then
             if ((res < min)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')${message}"
             fi
         elif [[ -n "$max" ]]; then
             if ((res > max)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')${message}"
             fi
         fi
         ;;
@@ -169,117 +225,67 @@ check() {
         val=${#val}
         if [[ -n "$min" ]] && [[ "$min" == "$max" ]]; then
             if ((val != min)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be exactly $min but »${res}« is $val characters long')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be exactly $min but »${res}« is $val characters long')${message}"
             fi
         elif [[ -n "$min" && -n "$max" ]]; then
             if ((val < min || val > max)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be between $min and $max but »${res}« is $val characters long')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be between $min and $max but »${res}« is $val characters long')${message}"
             fi
         elif [[ -n "$min" ]]; then
             if ((val < min)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be at least $min but »${res}« is $val characters long')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be at least $min but »${res}« is $val characters long')${message}"
             fi
         elif [[ -n "$max" ]]; then
             if ((val > max)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be not more than $max but »${res}« is $val characters long')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be not more than $max but »${res}« is $val characters long')${message}"
             fi
         fi
         ;;
     enum)
-        [ -n "$allow" ] || die "$(gettext "A list with --allow=<words> is needed for enum check")"
+        [ -n "$allow" ] || die "$(gettext "A list with --allow=<words> is needed for enum check")${message}"
         if [[ " $allow " != *" $val "* ]]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext '"$name" is set to "${val}" but has to be one of: $allow')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext '"$name" is set to "${val}" but has to be one of: $allow')${message}"
         fi
         ;;
     date)
         if ! res=$(date_format unix "$val"); then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be a parsable date format but »${val}« was given')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be a parsable date format but »${val}« was given')${message}"
         fi
         ;;
     duration)
         [[ "$res" =~ ^-?[0-9] ]] && res="$(duration_format seconds "$val")" || true
         if [[ ! "$res" =~ ^-?[0-9]+$ ]]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be an integer or human duration but »${val}« was given')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be an integer or human duration but »${val}« was given')${message}"
         fi
         ;;
     path)
         if [ ! -e "$val" ]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" ${val} has to be an existing path')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" ${val} has to be an existing path')${message}"
         fi
         ;;
     file)
         if [ ! -f "$val" ]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" ${val} has to be an existing file')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" ${val} has to be an existing file')${message}"
         fi
         ;;
     directory)
         if [ ! -d "$val" ]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" ${val} has to be an existing directory')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" ${val} has to be an existing directory')${message}"
         fi
         ;;
     readable)
         if [ ! -r "$val" ]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" ${val} has to be a file readable for user')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" ${val} has to be a file readable for user')${message}"
         fi
         ;;
     writable)
         if [ ! -w "$val" ]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" ${val} has to be a file writable for user')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" ${val} has to be a file writable for user')${message}"
         fi
         ;;
     *) die "$(eval_gettext 'A check named ${check} is not defined')" ;;
     esac
-    printf '%s' "$res"
-}
-
-# Validate and sanitize values.
-#
-# This validation is possible using the @check and `is` function.
-# - @check should be used for sanitize because it will output the value
-# - `is` should be used for checking only validity or stop processing on problem because no value is output
-#
-# Every parameter should be checked to prevent failure later in the code.
-# For such checks you run it with the `--die` option to stop processing if wrong.
-# But you can also use it in the program flow without that and use it's return status to check if it 0=ok or 1=failed.
-#
-# Because the values may start with an dash you should always put it at the end after '--' to prevent parsing it as option.
-#
-# The following checks are implemented:
-#
-# - `set` will fail if no value given
-# - `empty` will fail if not empty like ""
-# - `bool` will transform the value to `1` or `0` and allows: true/false, t/f, 1/0, yes/no, y/j/n, ja/nein, ""
-# - `true` should be a boolean true
-# - `false` should be a boolean false
-# - `integer` will check for a number maybe within a range
-# - `float` will check for a number maybe within a range
-# - `enum' will check against valid words using `--allow="word1 word2"`
-# - `length` check that the length is within range (like integer)
-# - `date` check that the input is parsable as date
-# - `duration` check and parse the @duration_format
-# - `path` check that value is an existing path (any type)
-# - `file` check that value is an existing file
-# - `directory` check that value is an existing directory
-# - `readable` check that value is a file readable by user
-# - `writable` check that value is a file writable by user
-#
-# Usage:    is <check> [options] -- <value>
-# Options:  d, die              # stop with error instead of return state
-#           n, name=<string>    # name the variable for the `die` message
-#           min=<num>           # for integer
-#           max=<num>           # for integer
-#           allow=<words>       # for enum (space separated)
-# Exit:     with message if incorrect value
-# Example:  Check arguments:
-#
-#           - `is integer --name=arguments --max=2 $#` # mostly only check max, if all args are checked separately
-#
-#           Use in code:
-#
-#           - `if is integer age --min=18 -- "$1"; then ...`
-#           - `if ! is integer "$DEBUG"; then ...`
-is() {
-    check "$@" >/dev/null
+    [ -z "$output" ] || printf '%s' "$res"
 }
 
 # Deprecated: Check that a specific number of parameters are given
