add ttl in mktemp

diff --git a/base b/base
--- a/base
+++ b/base
@@ -63,6 +63,97 @@ BASHLIB_HOME=${BASHLIB_HOME:-$HOME/bashlib}
 CC_RESET=$'\033[0m'
 CC_CRITICAL=$'\033[1;45m'
 CC_BLACK=$'\033[30m'
+declare -F "is_integer" >/dev/null||source "$BASHLIB_HOME"/module/validator
+now(){
+date +%s
+}
+date_diff(){
+local start end
+num_parameters "$@" --min 2 --max 2 --die "Need exactly two parameters: diff_sec <start> <end>"
+is_integer "$1"&&start=${1-}||start=$(date -d "$1" +%s)||die "Date format '$1' not parsable!"
+is_integer "$2"&&end=${2-}||end=$(date -d "$2" +%s)||die "Date format '$2' not parsable!"
+echo $((end-start))
+}
+date_format(){
+local value format
+case $1 in
+iso)format="--iso-8601=seconds";;
+iso-date)format="--iso-8601";;
+zulu)format="-u +%Y-%m-%dT%H:%M:%SZ";;
+sql)format='+"%Y-%m-%d %H:%M:%S"';;
+unix)format="+%s";;
+eu-date)format="+%Y-%m-%d";;
+us-date)format="+%m/%d/%Y";;
+human-date)format="+%A, %B %d, %Y";;
+time)format="%H:%M:%S";;
+time-short)format="%H:%M";;
+*)format="$1"
+esac
+[ -n "$2" ]&&value="${2-}"||value=$(now)
+is_integer "$value"&&eval "date -d @$value $format"||eval "date -d \"$value\" $format"||die "Date format '$value' not parsable!"
+}
+duration_format(){
+local value
+is_integer "$2"&&value="$2"||value="$(_parse_duration "$2")"
+case $1 in
+seconds)echo "$value";;
+minutes)echo $((value/60));;
+hours)echo $((value/3600));;
+days)echo $((value/86400));;
+human)_format_duration "$value"
+esac
+}
+_parse_duration(){
+local input="$1"
+local total=0
+local overall_sign=1
+local value unit vnum
+if [[ $input == -* ]];then
+overall_sign=-1
+input="${input#-}"
+elif [[ $input == +* ]];then
+overall_sign=1
+input="${input#+}"
+fi
+while read -r value unit;do
+if [[ $value =~ ^[+-] ]];then
+vnum="$value"
+else
+vnum=$((overall_sign*value))
+fi
+case "$unit" in
+''|s|sec|secs|second|seconds)total=$((total+vnum));;
+m|min|mins|minute|minutes)total=$((total+vnum*60));;
+h|hr|hrs|hour|hours)total=$((total+vnum*3600));;
+d|day|days)total=$((total+vnum*86400));;
+w|week|weeks)total=$((total+vnum*604800));;
+*)printf "$(gettext 'Invalid duration unit'): %s\n" "$unit" >&2
+return 1
+esac
+done < <(grep -Eo '[+-]?[0-9]+[[:alpha:]]*' <<<"$input"|sed -E 's/^([+-]?[0-9]+)([[:alpha:]]*)$/\1 \2/')
+printf '%d\n' "$total"
+}
+_format_duration(){
+local total="$1"
+local sign=""
+if ((total<0));then
+sign="-"
+total=$((-total))
+fi
+local w=$((total/604800))
+local d=$((total/86400))
+local h=$(((total%86400)/3600))
+local m=$(((total%3600)/60))
+local s=$((total%60))
+local out=""
+((w))&&out+="${w}w"
+((d))&&out+="${d}d"
+((h))&&out+="${h}h"
+((m))&&out+="${m}m"
+((s))&&out+="${s}s"
+[[ -z $out ]]&&out="0s"&&sign=""
+echo "$sign$out"
+}
 export TEXTDOMAIN=bashlib
 export TEXTDOMAINDIR=$BASHLIB_HOME/locale
 source gettext.sh
@@ -122,7 +213,7 @@ shift 2
 -r|--random)rand=$RANDOM
 shift
 ;;
--T|--ttl)ttl="$2"
+-T|--ttl)ttl="$(duration_format seconds "$2")"
 shift 2
 ;;
 --)shift
@@ -143,4 +234,16 @@ else
 touch "$result"
 fi
 echo "$result"
+debug "$result"
+[ -z "$ttl" ]||(_rmtemp "$ttl" "$result" >/dev/null 2>&1&
+disown)
+}
+_rmtemp(){
+local wait="$1" file="$2"
+while [ -e "$result" ]&&((wait>0));do
+sleep 1
+debug "$wait"
+((wait--))
+done
+[ ! -e "$result" ]||rm -r "$result"
 }
