show failed modules in docker test

diff --git a/check b/check
--- a/check
+++ b/check
@@ -20,7 +20,7 @@ while true; do
     ((total > ok + skip + fail)) || total="${CC_NOTICE}${total}${CC_RESET}"
     ((ok == 0)) || ok="${CC_OK}${ok}${CC_RESET}"
     ((fail == 0)) || fail="${CC_ERROR}${fail}${CC_RESET}"
-    echo -en "$dist ${total}/$ok/$fail "
+    echo -en "$dist ${total}/$ok/$fail ${CC_ERROR}$(grep -l "^not ok" "$dir"/* | sed 's#.*/##;s#\..*##' | xargs echo || true)${CC_RESET}"
   done
   sleep 2
   printf '%b' $'\e[1K\r'
diff --git a/test b/test
--- a/test
+++ b/test
@@ -83,14 +83,14 @@ else
           ((fail == 0)) || fail="${CC_ERROR}${fail}${CC_RESET}"
           printf '%b' $'\e[1K\r'
           echo -n "Running ${CC_CYAN_BOLD}${name^} $version${CC_RESET}... "
-          echo -en "${total}/$ok/$fail "
+          echo -en "${total}/$ok/$fail ${CC_ERROR}$(grep -l "^not ok" "$dir"/* | sed 's#.*/##;s#\..*##' | xargs echo || true)${CC_RESET}"
         else
           printf '%b' $'\e[1K\rinitializing...'
         fi
         sleep 2
       done
       printf '%b' $'\e[1K\r'
-      echo "Finished ${CC_CYAN_BOLD}${name^} $version${CC_RESET} with ${total}/$ok/$fail "
+      echo "Finished ${CC_CYAN_BOLD}${name^} $version${CC_RESET} with ${total}/$ok/$fail ${CC_ERROR}$(grep -l "^not ok" "$dir"/* | sed 's#.*/##;s#\..*##' | xargs echo || true)${CC_RESET}"
       #rm -rf tests/results/${name}-${version} 2>/dev/null || true
       cp -r /tmp/bashlib-docker/tests/results/${name}-${version} tests/results
     done
