fix mattermost to work with spaces in channel names

diff --git a/full b/full
--- a/full
+++ b/full
@@ -1072,12 +1072,14 @@ fi
 echo "${_mattermost_cache["__t_$1"]}"
 }
 _mattermost_channel(){
-if [[ ! -v _mattermost_cache["channel_$1_$2"] ]];then
+local cache="channel_$1_$2"
+cache=${cache//[^a-zA-Z0-9_]/}
+if [[ ! -v _mattermost_cache[$cache] ]];then
 debug "GET mattermost/users/me/teams/<team-id>/channels"
-_mattermost_cache["channel_$1_$2"]="$(curl -H "Authorization: Bearer $MATTERMOST_TOKEN" "$MATTERMOST_API"/users/me/teams/"$1"/channels|jq '.[] | select(.display_name == "'"$2"'") | .id' -r)"||die "Could not get ID of channel $1/$2 in mattermost!"
+_mattermost_cache[$cache]="$(curl -H "Authorization: Bearer $MATTERMOST_TOKEN" "$MATTERMOST_API"/users/me/teams/"$1"/channels|jq '.[] | select(.display_name == "'"$2"'") | .id' -r)"||die "Could not get ID of channel $1/$2 in mattermost!"
 fi
-[ -n "${_mattermost_cache["channel_$1_$2"]}" ]||die "Channel $2 does not exist in mattermost (team $1)"
-echo "${_mattermost_cache["channel_$1_$2"]}"
+[ -n "${_mattermost_cache[$cache]}" ]||die "Channel $2 does not exist in mattermost (team $1)"
+echo "${_mattermost_cache[$cache]}"
 }
 _mattermost_channel_bypost(){
 debug "GET mattermost/posts/<post-id>"
