fix alerts if no summary there

diff --git a/full b/full
--- a/full
+++ b/full
@@ -841,16 +841,16 @@ local filter="" quiet
 eval set -- "$(option_parse $'a alertname +\ni instance +\nn net +\ns summary +\nq quiet -' "$@")"
 while true;do
 case "$1" in
--i|--instance)[ -z "$2" ]||filter="$filter | select(.labels.instance|test(\"$2\"))"
+-i|--instance)[ -z "$2" ]||filter="$filter | select(.labels.instance|test(\"$2\"; \"i\"))"
 shift 2
 ;;
--a|--alertname)[ -z "$2" ]||filter="$filter | select(.labels.alertname|test(\"$2\"))"
+-a|--alertname)[ -z "$2" ]||filter="$filter | select(.labels.alertname|test(\"$2\"; \"i\"))"
 shift 2
 ;;
--s|--summary)[ -z "$2" ]||filter="$filter | select(.annotations.summary|test(\"$2\"))"
+-s|--summary)[ -z "$2" ]||filter="$filter | select(.annotations.summary? // \"\"|test(\"$2\"; \"i\"))"
 shift 2
 ;;
--n|--net)[ -z "$2" ]||filter="$filter | select(.labels.net==\"$2\")"
+-n|--net)[ -z "$2" ]||filter="$filter | select(.labels.net? // \"\"|test(\"$2\"; \"i\"))"
 shift 2
 ;;
 -q|--quiet)quiet=1
@@ -864,7 +864,8 @@ esac
 done
 install jq mlr
 local list
-list="$(curl -H "Authorization: Bearer $GRAFANA_TOKEN" "$GRAFANA_API/alertmanager/grafana/api/v2/alerts"|jq 'sort_by(.startsAt) | .[] '"$filter")"||die "Could not get alerts from Grafana!"
+list="$(curl -H "Authorization: Bearer $GRAFANA_TOKEN" "$GRAFANA_API/alertmanager/grafana/api/v2/alerts")"||die "Could not get alerts from Grafana!"
+list="$(jq 'sort_by(.startsAt) | .[] '"$filter" <<<"$list")"||die "Parse error in Grafana alerts list with filter: $filter"
 local format=${1:-console}
 [ -n "$list" ]||return 0
 [ -z "$quiet" ]||return 1
