optimize tasks

diff --git a/full b/full
--- a/full
+++ b/full
@@ -201,10 +201,12 @@ CC_BLUE_BOLD_BG=$'\033[104m'
 CC_MAGENTA_BOLD_BG=$'\033[105m'
 CC_CYAN_BOLD_BG=$'\033[106m'
 color_256(){
-echo $'\033[38;5;'${1:-0}'m'
+local num="${1//[!0-9]/}"
+echo $'\033[38;5;'"${num:-0}"'m'
 }
 color_256_bg(){
-echo $'\033[48;5;'${1:-0}'m'
+local num="${1//[!0-9]/}"
+echo $'\033[48;5;'"${num:-0}"'m'
 }
 CC_CRITICAL=$'\033[1;45m'
 CC_ERROR=$'\033[1;31m'
@@ -231,17 +233,17 @@ echo -e "\t${CC_INVERSE}CC_INVERSE$CC_RESET"
 echo "256 Color palette:"
 local cols=15
 local rows=15
-for c in $(seq 0 $cols);do
-for r in $(seq 0 $rows);do
+for c in $(seq 0 "$cols");do
+for r in $(seq 0 "$rows");do
 num=$((r*cols+c))
-echo -ne "\t$(color_256 $num)FG $num"
+echo -ne "\t$(color_256 "$num")FG $num"
 done
 echo ""
 done
-for c in $(seq 0 $cols);do
-for r in $(seq 0 $rows);do
+for c in $(seq 0 "$cols");do
+for r in $(seq 0 "$rows");do
 num=$((r*cols+c))
-echo -ne "\t$(color_256_bg $num)BG $num$CC_RESET"
+echo -ne "\t$(color_256_bg "$num")BG $num$CC_RESET"
 done
 echo ""
 done
@@ -254,6 +256,7 @@ echo -e "\t${CC_OK}CC_OK$CC_RESET"
 echo -e "\t${CC_HEADING}CC_HEADING$CC_RESET"
 echo -e "\t${CC_INVERS}CC_INVERS$CC_RESET"
 }
+declare -F "is_integer" >/dev/null||source "$BASHLIB_HOME"/module/validator
 now(){
 date +%s
 }
@@ -936,11 +939,14 @@ fi
 done
 }
 tasks(){
-local end title
-eval set -- "$(option_parse $'t title +' "$@")"
+local end title default
+eval set -- "$(option_parse $'t title +\nd default +' "$@")"
 while true;do
 case "$1" in
 -t|--title)title="-t$2" >/dev/tty
+shift 2
+;;
+-d|--default)default="$2" >/dev/tty
 shift 2
 ;;
 --)shift
@@ -949,11 +955,34 @@ break
 *)die "$(gettext 'Unrecognized option: $1')"
 esac
 done
-local list task
-[ $# -eq 1 ]||list="$(input_lines "$@")"
+local list task num newlist opt cmd name res
+list="$(input_lines "$@")"
+while grep -qv '|' <<<"$list";do
+newlist=""
+while IFS= read -r line;do
+IFS='|' read -r cmd name <<<"$line"
+if [ -n "$name" ];then
+newlist="$newlist$line"$'\n'
+else
+echo ">>> $cmd"
+res="$($cmd)"||die "Could not get task list from command: $cmd"
+[ -z "$res" ]||newlist="$newlist$res"$'\n'
+fi
+done <<<"$list"
+list="$(echo "$newlist"|sed '/^[[:space:]]*$/d')"
+done
+if [ "$default" = "x" ];then
+opt="-d x"
+elif [ -n "$default" ];then
+num=0
+while IFS= read -r line;do
+((num++))||true
+IFS='|' read -r cmd name <<<"$line"
+[ ! "$default" = "$(trim "$cmd")" ]||opt="-d $num"
+done <<<"$list"
+fi
 while true;do
-[ -z "$1" ]||list="$("$1")"
-task=$(choose "$title" -x Beenden "$list")
+task=$(choose "$title" -x Beenden $opt "$list")
 [[ $task != "exit" ]]||break
 $task||die "Got error $? running: $task"
 echo ""
@@ -1258,7 +1287,7 @@ _queue_control&
 _queue_control_pid=$!
 fi
 }
-declare -F "num_parameters" >/dev/null||source $BASHLIB_HOME/module/validator
+declare -F "num_parameters" >/dev/null||source "$BASHLIB_HOME"/module/validator
 remote(){
 local ssh="${slogin:-operator}@$server"
 if [ -p /dev/stdin ];then
@@ -1522,5 +1551,73 @@ else
 echo $num
 fi
 [ $num -eq 0 ]&&return 0||return 1
+}
+num_parameters(){
+eval set -- "$(option_parse $'- min +\n- max +\n- die +' "$@")"
+local min max die
+while true;do
+case "$1" in
+--min)min=$2
+shift 2
+;;
+--max)max=$2
+shift 2
+;;
+--die)die=$2
+shift 2
+;;
+--)shift
+break
+;;
+*)die "$(gettext 'Unrecognized option: $1')"
+esac
+done
+_die(){
+read -r line func file <<<"$(caller 1)"
+echo "Check ${FUNCNAME[1]}: $1 ($func in $file:$line)" >&2
+[ -z "$die" ]||die "$die"
+return 1
+}
+[ -z "$min" ]||[ "$#" -ge "$min" ]||_die "[$*] $# < $min"||return 1
+[ -z "$max" ]||[ "$#" -le "$max" ]||_die "[$*] $# > $max"||return 1
+}
+is_success(){
+num_parameters --min 1 --max 1 --die "Only one argument allowed, got: $#" -- "$@"
+return $1
+}
+is_empty(){
+num_parameters --max 1 --die "Only one argument allowed, got: $#" -- "$@"
+[ -z "$1" ]
+}
+is_integer(){
+num_parameters --min 1 --max 1 --die "Only one argument allowed, got: $#" -- "$@"
+[[ $1 =~ ^-?[0-9]+$ ]]
+}
+is_float(){
+num_parameters --min 1 --max 1 --die "Only one argument allowed, got: $#" -- "$@"
+[[ $1 =~ ^[-+]?[0-9]+([.][0-9]+)?$ ]]
+}
+compare(){
+num_parameters --min 3 --max 3 --die "Exactly 3 parameter needed, got: $#" -- "$@"
+case "$2" in
+=|==)[[ $1 == $3 ]];;
+!=)[[ $1 != $3 ]];;
+=~)[[ $1 =~ $3 ]];;
+!~)[[ ! $1 =~ $3 ]];;
+*)[ "$1" $2 "$3" ]
+esac
+}
+trim_start(){
+local str="${1-}"
+local char="${2:-[:space:]}"
+echo "${str#"${str%%[!$char]*}"}"
+}
+trim_end(){
+local str="${1:-}"
+local char="${2:-[:space:]}"
+echo "${str%"${str##*[!$char]}"}"
+}
+trim(){
+trim_end "$(trim_start "$1" "$2")" "$2"
 }
 source /home/alex/dvb/bash-lib/configs
diff --git a/module/output b/module/output
--- a/module/output
+++ b/module/output
@@ -317,14 +317,22 @@ choose() {
 }
 
 # Run tasks as selected by user
-# Usage:    tasks <function>"|"<entry>"...  # entries from arguments
-#           <list> | tasks                  # entries from pipe
-#           tasks <function>                # entries from function (dynamic)
+# Often the functions are also named `check-...` for the ones which will return tasks and `task-...` for the ones really doing the job. The first one may do a lot of analyzation and output user information on stdout.
+# The '|' character is not possible within the commans. If a pipe is neccessary put it within a function.
+# Usage:    tasks <entry>...
+#           # <entry>       := <check-fn> or "<task-line>"
+#           # <check-fn>    := function called to return up to multiple <task-lines>
+#           # <task-fn>     := function to be run when selected
+#           # <task-line>   := "<task-fn> | <name>"
+#           <task-lines> | tasks            # entries from pipe
+#           tasks <check-fn>                # add entries from function (dynamic)
 # Option    -t, --title <title>             # display text line above selection
+#           -d, --default <task-fn> | "x"   # default command to start
 # TTY:      [<title>]
-#           <list>
+#           1) <name>
 #           ...
-#           <question> <key>
+#           x) Beenden
+#           <question> <input>
 # Example:  list_tasks() {
 #               # can be created dynamically:
 #               cat <<'EOC'
@@ -341,12 +349,16 @@ choose() {
 #           tasks -t "Nächste Schritte" list_tasks
 tasks() {
     # parameter parsing
-    local end title
-    eval set -- "$(option_parse $'t title +' "$@")"
+    local end title default
+    eval set -- "$(option_parse $'t title +\nd default +' "$@")"
     while true; do
         case "$1" in
         -t | --title)
             title="-t$2" >/dev/tty
+            shift 2
+            ;;
+        -d | --default)
+            default="$2" >/dev/tty
             shift 2
             ;;
         --)
@@ -357,11 +369,37 @@ tasks() {
         esac
     done
     # processing
-    local list task
-    [ $# -eq 1 ] || list="$(input_lines "$@")"
+    local list task num newlist opt cmd name res
+    list="$(input_lines "$@")"
+    # check for dynamic parts in list
+    while grep -qv '|' <<<"$list"; do
+        newlist=""
+        while IFS= read -r line; do
+            IFS='|' read -r cmd name <<<"$line"
+            if [ -n "$name" ]; then
+                newlist="$newlist$line"$'\n'
+            else
+                echo ">>> $cmd"
+                res="$($cmd)" || die "Could not get task list from command: $cmd"
+                [ -z "$res" ] || newlist="$newlist$res"$'\n'
+            fi
+        done <<<"$list"
+        list="$(echo "$newlist" | sed '/^[[:space:]]*$/d')"
+    done
+    if [ "$default" = "x" ]; then
+        opt="-d x"
+    elif [ -n "$default" ]; then
+        num=0
+        while IFS= read -r line; do
+            ((num++)) || true
+            IFS='|' read -r cmd name <<<"$line"
+            [ ! "$default" = "$(trim "$cmd")" ] || opt="-d $num"
+        done <<<"$list"
+    fi
+    # ask user to select
     while true; do
-        [ -z "$1" ] || list="$("$1")"
-        task=$(choose "$title" -x Beenden "$list")
+        # shellcheck disable=SC2086
+        task=$(choose "$title" -x Beenden $opt "$list")
         [[ "$task" != "exit" ]] || break
         $task || die "Got error $? running: $task"
         echo ""
