optimize code

diff --git a/full b/full
--- a/full
+++ b/full
@@ -34,7 +34,7 @@ opt_descriptions[$name]="$desc"
 opt_type[$name]=$type
 opt_short[$name]=$opt
 done <<<"$1"
-echo "$(gettext "Options"):"
+printf '%s\n' "$(gettext "Options"):"
 for name in "${!opt_descriptions[@]}";do
 local type_text=""
 local short_text=""
@@ -48,28 +48,24 @@ printf "  %-40s %s\n" "$short_text--$name$type_text" "${opt_descriptions[$name]}
 done
 }
 input(){
-test -p /dev/stdin&&(($#==0))&&cat -||echo "$*"
+test -p /dev/stdin&&(($#==0))&&cat -||printf '%s' "$*"
 }
 input_args(){
 local num=${1-}
 local start=$((num+2))
 is set --name="num" --die -- "$num"
 ((num>0))||die "<num>=$num $(gettext 'argument is not a valid number!')"
-test -p /dev/stdin&&(($#<num+2))&&cat -||echo "${@:start}"
+test -p /dev/stdin&&(($#<num+2))&&cat -||echo -n "${@:start}"
 }
 input_lines(){
 if [ -p /dev/stdin ]&&is empty -- "$1";then
 cat -
 else
-for arg in "$@";do echo "$arg";done
+printf '%s\n' "$@"
 fi
 }
 escape_args(){
-local escaped_args=()
-for arg in "$@";do
-escaped_args+=("$(printf '%q' "$arg")")
-done
-echo "${escaped_args[*]}"
+printf '%q\n' "$@"
 }
 contains(){
 _deprecated "use array <array-name> has <value>"
@@ -92,7 +88,7 @@ return 1
 indexof)for i in "${!arr[@]}"
 do
 if [ "${arr[i]}" = "$value" ];then
-echo "$i"
+printf '%s' "$i"
 return 0
 fi
 done
@@ -108,7 +104,7 @@ local joined="${array[0]}"
 for element in "${array[@]:1}";do
 joined+="$sep$element"
 done
-echo "$joined"
+printf '%s' "$joined"
 }
 split(){
 is integer --name=arguments --max=3 --die -- $#
@@ -139,7 +135,7 @@ simple)key="${3//[^a-zA-Z0-9_]/_}"
 esac
 case "$cmd" in
 set)is set --name=key --die -- "$3"&&arr["$key"]="$value";;
-get)is set --name=key --die -- "$3"&&echo "${arr["$key"]}";;
+get)is set --name=key --die -- "$3"&&printf '%s' "${arr["$key"]}";;
 unset)is set --name=key --die -- "$3"&&unset 'arr[$key]';;
 has)is set --name=key --die -- "$3"&&[[ -v arr["$key"] ]];;
 contains)is set --name=value --die -- "$3"
@@ -235,14 +231,14 @@ local rows=15
 for c in $(seq 0 "$cols");do
 for r in $(seq 0 "$rows");do
 num=$((r*cols+c))
-echo -ne "\t$(color_256 "$num")FG $num"
+printf "\t$(color_256 "$num")FG $num"
 done
 echo ""
 done
 for c in $(seq 0 "$cols");do
 for r in $(seq 0 "$rows");do
 num=$((r*cols+c))
-echo -ne "\t$(color_256_bg "$num")BG $num$CC_RESET"
+printf "\t$(color_256_bg "$num")BG $num$CC_RESET"
 done
 echo ""
 done
@@ -270,17 +266,17 @@ local start end
 end="${2:-$(now)}"
 is integer -- "$1"&&start="$1"||start=$(date -d "$1" +%s)||die "Date format '$1' not parsable!"
 is integer -- "$end"&&end="$end"||end=$(date -d "$end" +%s)||die "Date format '$2' not parsable!"
-echo $((end-start))
+printf '%s' $((end-start))
 }
 date_format(){
 is integer --name=arguments --max=2 --die -- $#
 is set --name=format --die -- "$1"
-local value format
+local value format opt
 case $1 in
 iso)format="-Iseconds";;
 iso-date)format="-I";;
-zulu)format="-u +%Y-%m-%dT%H:%M:%SZ";;
-sql)format='+"%Y-%m-%d %H:%M:%S"';;
+zulu)opt="-u"&&format="+%Y-%m-%dT%H:%M:%SZ";;
+sql)format="+%Y-%m-%d %H:%M:%S";;
 unix)format="+%s";;
 eu-date)format="+%Y-%m-%d";;
 us-date)format="+%m/%d/%Y";;
@@ -291,7 +287,7 @@ time-short)format="+%H:%M";;
 *)format="+$1"
 esac
 value="${2-$(now)}"
-is integer -- "$value"&&eval "date -d @$value '$format'"||eval "date -d \"$value\" '$format'"||die "Date format '$value' not parsable!"
+is integer -- "$value"&&eval "date -d @$value '$format'"||eval "date -d \"$value\" $opt '$format'"||die "Date format '$value' not parsable!"
 }
 sleep_until(){
 is integer --name=arguments --max=1 --die -- $#
@@ -307,10 +303,10 @@ is enum --name=format --allow="seconds minutes hours days human" --die -- "$1"
 local value
 is integer -- "$2"&&value="$2"||value="$(_parse_duration "$2")"
 case $1 in
-seconds)echo "$value";;
-minutes)echo $((value/60));;
-hours)echo $((value/3600));;
-days)echo $((value/86400));;
+seconds)printf '%s' "$value";;
+minutes)printf '%s' $((value/60));;
+hours)printf '%s' $((value/3600));;
+days)printf '%s' $((value/86400));;
 human)_format_duration "$value"
 esac
 }
@@ -363,7 +359,7 @@ local out=""
 ((m))&&out+="${m}m "
 ((s))&&out+="${s}s "
 is empty -- "$out"&&out="0s"&&sign=""||true
-echo "$sign${out% }"
+printf '%s' "$sign${out% }"
 }
 _timer_start=0
 timer(){
@@ -371,7 +367,7 @@ case $1 in
 start)_timer_start=$(date +%s.%N)
 ;;
 stop)local seconds nano len
-IFS='.' read -r seconds nano <<<"$(echo "$(date +%s.%N) - $_timer_start"|bc)"
+IFS='.' read -r seconds nano < <(printf '%s' "$(date +%s.%N) - $_timer_start"|bc)
 len=$((4-${#seconds}))
 ((len>=0))||len=0
 LANG=C printf "%0.${len}f\n" "$seconds.$nano"
@@ -1407,7 +1403,7 @@ read -n 1 -s -r _ </dev/tty
 else
 stty -echo </dev/tty
 while ((timeout>0));do
-echo -ne "\r$CC_NOTICE$text$CC_RESET $(duration_format human "$timeout")     "
+printf "\r%s" "$CC_NOTICE$text$CC_RESET $(duration_format human "$timeout")     "
 if read -r -s -t 1 -n 1 _ </dev/tty;then
 if [ -n "$abort" ];then
 echo -e "\b\b\b\b$(gettext 'aborted by user')    "
@@ -1416,7 +1412,7 @@ return 1
 fi
 fi
 ((timeout--))
-((timeout>0))||echo -ne "\r$CC_NOTICE$text$CC_RESET 0s      "
+((timeout>0))||printf "\r%s" "$CC_NOTICE$text$CC_RESET 0s      "
 done
 stty echo </dev/tty
 fi
@@ -3474,6 +3470,25 @@ num="$(basename "$file")"
 queue add _trivy_report "$work" "$file" "$source"
 done
 queue run
+rm -r "$work"/split
+for folder in $(find "$work" -mindepth 3 -type d);do
+cat "$folder/header.txt" "$folder/sources.txt" "$folder/footer.txt" >"$folder/report.txt"
+rm "$folder/header.txt" "$folder/sources.txt" "$folder/footer.txt"
+cat "$folder/report.tsv" >>"$work"/list.tsv
+rm "$folder/report.tsv"
+if is file -- "$folder/expired.tsv";then
+cat "$folder/expired.tsv" >>"$work"/expired.tsv
+rm "$folder/expired.tsv"
+fi
+if is file -- "$folder/blocked.tsv";then
+cat "$folder/blocked.tsv" >>"$work"/blocked.tsv
+rm "$folder/blocked.tsv"
+fi
+if is file -- "$folder/prom.txt";then
+cat "$folder/prom.txt" >>"$work"/prom.txt
+rm "$folder/prom.txt"
+fi
+done
 echo "$work"
 }
 trivy_test(){
@@ -3503,6 +3518,24 @@ num="$(basename "$file")"
 queue add _trivy_report "$work" "$file" "$source"
 done
 queue run
+for folder in $(find "$work" -mindepth 3 -type d);do
+cat "$folder/header.txt" "$folder/sources.txt" "$folder/footer.txt" >"$folder/report.txt"
+rm "$folder/header.txt" "$folder/sources.txt" "$folder/footer.txt"
+cat "$folder/report.tsv" >>"$work"/list.tsv
+rm "$folder/report.tsv"
+if is file -- "$folder/expired.tsv";then
+cat "$folder/expired.tsv" >>"$work"/expired.tsv
+rm "$folder/expired.tsv"
+fi
+if is file -- "$folder/blocked.tsv";then
+cat "$folder/blocked.tsv" >>"$work"/blocked.tsv
+rm "$folder/blocked.tsv"
+fi
+if is file -- "$folder/prom.txt";then
+cat "$folder/prom.txt" >>"$work"/prom.txt
+rm "$folder/prom.txt"
+fi
+done
 }
 _trivy_cache=/tmp/trivy-cache
 declare -A _trivy_jira
@@ -3511,7 +3544,7 @@ debug "trivy_report \"$1\" \"$2\" \"$3\""
 local work="$1"
 local file="$2"
 local source="$3"
-local type severity target id json title pkgPath description cvss installed sourceLine date
+local type severity target id json title pkgPath description cvss installed sourceLine date fixed fixStatus links
 json="$(cat "$file")"
 type="$(jq .Type -r <<<"$json")"
 severity="$(jq .Severity -r <<<"$json")"
@@ -3524,8 +3557,13 @@ description="$(jq .Description -r <<<"$json")"
 cvss="$(jq '.CVSS[]?.V3Score' -r <<<"$json")"|tr $'\n' '\;'|sed 's/;$//;s/;/; /g'
 installed="$(jq .InstalledVersion -r <<<"$json")"
 sourceLine="$source $target ($type) $pkgPath - Version $installed"
+fixed="$(jq .FixedVersion -r <<<"$json")"
+[ "$fixed" != "null" ]||fixed="-"
+fixStatus="$(jq .Status -r <<<"$json")"
+[ "$fixStatus" != "null" ]||fixStatus="-"
 date="$(jq .PublishedDate -r <<<"$json")"
 test ! "$date" = "null"||date=""
+links="$(jq '.References[]?' -r <<<"$json"|sed 's/^/- /')"
 local changes=() rules=() action
 if (($(date_format unix "$date")>$(now)-$(duration_format seconds 3d)))&&[[ $severity == "HIGH" || $severity == "CRITICAL" ]];then
 action="Downgrade $severity -> MEDIUM because it was published less than 3 days ago"
@@ -3547,14 +3585,10 @@ info "$id at $target: $action" >&2
 changes+=("{\"Severity\": \"MEDIUM\",\"OriginalSeverity\": \"$severity\"}")
 rules+=("{\"Title\": \"NPM Dev Dependency\",\"Description\": \"$action.\"}")
 fi
+local issue key approval comments expired
 if is set -- "$TRIVY_JIRA_BOARD"&&[[ $severity == "HIGH" || $severity == "CRITICAL" ]];then
-local issue created fixed fixStatus links
+local created
 issue="$(jira search "project = ${_trivy_jira[board]} AND summary ~ $id ORDER BY created ASC"|head -1)"
-fixed="$(jq .FixedVersion -r <<<"$json")"
-[ "$fixed" != "null" ]||fixed="-"
-fixStatus="$(jq .Status -r <<<"$json")"
-[ "$fixStatus" != "null" ]||fixStatus="-"
-links="$(jq '.References[]?' -r <<<"$json"|sed 's/^/- /')"
 if is empty -- "$issue";then
 local fields priority=Low
 case $severity in
@@ -3575,16 +3609,26 @@ jira json fields set labels json "[\"cve\", \"$(sed 's#.*ekz.de/##;s#/-/.*##;s#[
 issue="$(jira create "$fields")"
 created=1
 fi
-local jira deploy commentDate
+local jira deploy commentDate jiraStatus assignee
 jira="$(jira get "$issue")"
 deploy="$(jq '.fields.'"${_trivy_jira[field_approval]}"'?.value' -r <<<"$jira")"
-commentDate=$(jq '.fields.comment.comments[].updated' -r <<<"$jira"|sort|tail -1)
+commentDate="$(jq '.fields.comment.comments[].updated' -r <<<"$jira"|sort|tail -1)"
+key="$(jq .key -r <<<"$jira")"
+jiraStatus="$(jq .fields.status.name -r <<<"$jira")"
+assignee="$(jq .fields.assignee.displayName -r <<<"$jira")"
+local date author comments=()
+while IFS=$'\t' read -r date author comment;do
+comments+=("$date $author: $(jira adf_to_md "$comment"|grep -v ^$)")
+done < <(jq '.fields.comment.comments[-3:][] | [.updated, .updateAuthor.displayName, (.body | @json)] | @tsv' -r <<<"$jira"|tac)
 if [[ $severity == "HIGH" || $severity == "CRITICAL" ]];then
-if ([ "$deploy" = "$TRIVY_JIRA_APPROVAL_IRRELEVANT" ]||([ "$deploy" = "$TRIVY_JIRA_APPROVAL_TEMP" ]&&(($(date_diff "$(now)" "$commentDate")<$(duration_format seconds '30d')))));then
+if ([ "$deploy" = "$TRIVY_JIRA_APPROVAL_IRRELEVANT" ]||([ "$deploy" = "$TRIVY_JIRA_APPROVAL_TEMP" ]&&(($(date_diff "$commentDate")<=$(duration_format seconds '30d')))));then
 action="Downgrade $severity -> MEDIUM because of Jira status '$deploy'"
 info "$id at $target: $action" >&2
 changes+=("{\"Severity\": \"MEDIUM\",\"OriginalSeverity\": \"$severity\"}")
 rules+=("{\"Title\": \"Jira Approval\",\"Description\": \"$action.\"}")
+fi
+if ([ "$deploy" = "$TRIVY_JIRA_APPROVAL_TEMP" ]&&(($(date_diff "$commentDate")>$(duration_format seconds '30d'))));then
+expired=1
 fi
 fi
 if ! is set -- "$created";then
@@ -3635,7 +3679,7 @@ fi
 fi
 action="Add information from Jira"
 info "$id at $target: $action" >&2
-changes+=("{\"Jira\": {\"id\": $issue, \"key\": $(jq .key <<<"$jira"), \"approval\": \"$deploy\", \"lastComment\": \"$commentDate\"}}")
+changes+=("{\"Jira\": {\"id\": $issue, \"key\": \"$key\", \"approval\": \"$deploy\", \"lastComment\": \"$commentDate\"}}")
 rules+=("{\"Title\": \"Jira Info\",\"Description\": \"$action.\"}")
 fi
 is empty -- "$rules"||changes+=("{\"Rules\": [$(join rules)]}")
@@ -3646,13 +3690,20 @@ severity="$(jq .Severity -r <<<"$json")"
 local folder="$work/${severity,,}/$type/$id"
 mkdir -p "$folder"
 echo "$json" >"$folder/data.json"
+local exploitDate exploitVendor exploitProduct issue key approval lastComment
+exploitDate="$(jq .Exploited.dateAdded -r <<<"$json")"
+test ! "$exploitDate" = "null"||exploitDate=""
+if is set -- "$exploitDate";then
+exploitVendor="$(jq .Exploited.vendorProject -r <<<"$json")"
+exploitProduct="$(jq .Exploited.product -r <<<"$json")"
+fi
 file="$folder/header.txt"
 if ! is file -- "$file";then
 case $severity in
-CRITICAL)echo -n "$CC_CRITICAL" >"$file";;
-HIGH)echo -n "$CC_ERROR" >"$file";;
-MEDIUM)echo -n "$CC_WARN" >"$file";;
-*)echo "" >"$file"
+CRITICAL)printf "$CC_CRITICAL" >"$file";;
+HIGH)printf "$CC_ERROR" >"$file";;
+MEDIUM)printf "$CC_WARN" >"$file";;
+*)printf "" >"$file"
 esac
 echo "================================================================================" >>"$file"
 echo "$severity $id $title" >>"$file"
@@ -3661,18 +3712,38 @@ echo "$description" >>"$file"
 echo "    " >>"$file"
 echo "Rating: $severity (CVSS Rating ${cvss:--})" >>"$file"
 echo "Status: Gefixt ab Version ${fixed:--} $fixStatus" >>"$file"
-debug "$date"
-debug "date $(date_format human-date "$date")"
-debug "age $(duration_format days "$(date_diff "$date")")"
 echo "Datum:  Sicherheitslücke bekannt seit $(date_format human-date "$date") (vor $(duration_format days "$(date_diff "$date")") Tagen)" >>"$file"
 echo "    " >>"$file"
+is empty -- "$exploitDate"||printf "Exploit bekannt seit $exploitDate bei $exploitVendor $exploitProduct\n\n" >>"$file"
+if is set -- "$issue";then
+printf "Jira Ticket: https://ekz-gruppe.atlassian.net/browse/$issue\n" >>"$file"
+printf "             $jiraStatus    Zuständig: $assignee\n" >>"$file"
+printf "             Deploy: ${approval:-Undefiniert}\n" >>"$file"
+printf "Letzte Kommentare:\n$(join comments $'\n'|sed 's/^/             /')" >>"$file"
+fi
 echo "Sources:" >>"$file"
 fi
 file="$folder/sources.txt"
 echo "- $sourceLine" >>"$file"
 file="$folder/footer.txt"
 if ! is file -- "$file";then
-true
+echo "Links:\n$links" >>"$file"
+printf "$CC_RESET"
+fi
+file="$folder/report.tsv"
+printf "$severity\t$type\t$id\t$title" >>"$file"
+is empty -- "$expired"||cat "$file" >"$folder/expired.tsv"
+[[ $severity == "LOW" || $severity == "MEDIUM" ]]||cat "$file" >"$folder/blocked.tsv"
+file="$folder/prom.txt"
+if [[ $severity == "HIGH" || $severity == "CRITICAL" ]];then
+case $severity in
+LOW)value=1;;
+MEDIUM)value=10;;
+HIGH)value=100;;
+CRITICAL)value=1000;;
+*)value=0
+esac
+echo "divibib_trivy_vulnerability{type=\"$type\",target=\"$target\",package=\"$pkgPath\",severity=\"$severity\",cve=\"$id\"} $value" >>"$file"
 fi
 }
 source $BASHLIB_HOME/configs
