fix some spelling

diff --git a/full b/full
--- a/full
+++ b/full
@@ -1544,15 +1544,15 @@ echo "$line"|cut -f1-3|sed "s#://#://$user:$pass@#"
 else
 echo "$line"|cut -f1-3
 fi
-done||(($?==141))||die "$(gettext "Could not get exporters from prometheus!")"
+done||(($?==141))||die "$(gettext "Could not get exporters from Prometheus!")"
 done
 }
 scrape(){
 local url="$1"
 num_parameters "$@" --min 1 --max 2 --die "Wrong number of parameters for scrape!"
-debug "Scrape the prometheus exporter at $1"
+debug "Scrape the Prometheus exporter at $1"
 local metrics
-metrics="$(curl "$url"|grep -Ev '^($|#)'||die "$(eval_gettext 'Could not scrape the prometheus exporter at $url!')")"
+metrics="$(curl "$url"|grep -Ev '^($|#)'||die "$(eval_gettext 'Could not scrape the Prometheus exporter at $url!')")"
 debug ">>> $metrics"
 local found=2
 echo "$metrics"|grep -E "$2"|grep '{'|sed 's/,\?[{}] \?/\t/g'||((found--))
@@ -2534,10 +2534,10 @@ host=${host:-$server}
 local ssh="$_login@$host"
 [ -z "$jump" ]||ssh="-J $jump $ssh"
 if [ -p /dev/stdin ];then
-ssh -t $ssh bash -s 2> >(grep -v '^Connection to .* closed\.' >&2)|nocr
+ssh -t $ssh bash -s 2> >(grep -v '^Connection to .* closed\.' >&2||true)|nocr
 return "${PIPESTATUS[0]}"
 else
-ssh -t $ssh "$@"|nocr
+ssh -t $ssh "$@" 2> >(grep -v '^Connection to .* closed\.' >&2||true)|nocr
 return "${PIPESTATUS[0]}"
 fi
 }
diff --git a/module/monitoring b/module/monitoring
--- a/module/monitoring
+++ b/module/monitoring
@@ -64,11 +64,11 @@ exporter() {
                 fi
             done ||
             (($? == 141)) ||
-            die "$(gettext "Could not get exporters from prometheus!")"
+            die "$(gettext "Could not get exporters from Prometheus!")"
     done
 }
 
-# Scrape prometheus exporter url now
+# Scrape Prometheus exporter url now
 # The metrics can be filtered by <pattern> argument.
 # Usage:    scrape <url> <pattern>
 # Stdout:   Tab separated list:
@@ -79,9 +79,9 @@ exporter() {
 scrape() {
     local url="$1"
     num_parameters "$@" --min 1 --max 2 --die "Wrong number of parameters for scrape!"
-    debug "Scrape the prometheus exporter at $1"
+    debug "Scrape the Prometheus exporter at $1"
     local metrics
-    metrics="$(curl "$url" | grep -Ev '^($|#)' || die "$(eval_gettext "Could not scrape the prometheus exporter at \$url!")")"
+    metrics="$(curl "$url" | grep -Ev '^($|#)' || die "$(eval_gettext "Could not scrape the Prometheus exporter at \$url!")")"
     debug ">>> $metrics"
     local found=2
     echo "$metrics" | grep -E "$2" | grep '{' | sed 's/,\?[{}] \?/\t/g' || ((found--))
@@ -89,7 +89,7 @@ scrape() {
     ((found > 0))
 }
 
-# Get grafana alerts
+# Get Grafana alerts
 # The list can be filtered by options and a specific output format can be selected.
 # Usage:    alerts [<format>]                       # tsv, json, console, mattermost
 #           alerts -i "^$server" console || echo "" # will print the alerts with an empty line if there are some
