start new table methods: csv and tsv

diff --git a/full b/full
--- a/full
+++ b/full
@@ -71,13 +71,31 @@ done
 echo "${escaped_args[*]}"
 }
 contains(){
-local -n array=$1
-local value=$2
-local e
-for e in "${array[@]}";do
-[[ $e != "$value" ]]||return 0
+_deprecated "use array <array-name> has <value>" warn
+array "$1" has "$2"
+}
+array(){
+declare -n arr="$1"
+local cmd=$2
+local value="$3"
+case "$cmd" in
+has)for e in "${arr[@]}"
+do
+[ ! "$e" = "$value" ]||return 0
 done
 return 1
+;;
+indexof)for i in "${!arr[@]}"
+do
+if [ "${arr[i]}" = "$value" ];then
+echo "$i"
+return 0
+fi
+done
+return 1
+;;
+*)die "Usage: array <array_name> {has|index} [<value>]"
+esac
 }
 join(){
 local -n array=$1
@@ -105,7 +123,7 @@ set)arr["$key"]="$value";;
 get)echo "${arr[$key]}";;
 unset)unset 'arr[$key]';;
 has)[[ -v arr[$key] ]];;
-*)die "Usage: hash <array_name> {set|get|unset|has} <key> [value]"
+*)die "Usage: hash <array_name> {set|get|unset|has} <key> [<value>]"
 esac
 }
 COLORS=$(tput colors 2>/dev/null||echo 0)
@@ -561,15 +579,6 @@ curl -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" -H "Content-Type: application/json" -
 }
 jira_update(){
 curl -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" -H "Content-Type: application/json" -X PUT "$JIRA_API/issue/$1" -d "$1"||die "Could not update Jira issue $1!"
-}
-_load_module module/software
-tsv2table(){
-install mlr
-input "$@"|mlr --csvlite --ifs '\t' -o pprint cat
-}
-tsv2md(){
-install mlr
-input "$@"|uncolorize|mlr --csvlite --ifs '\t' --omd cat
 }
 _load_module module/software
 mongo(){
@@ -2590,12 +2599,6 @@ done
 [ -n "$quiet" ]||echo ""
 }
 declare -Ag _software_install
-installed(){
-for cmd in "$@";do
-command -v "$cmd" >/dev/null||return 1
-done
-return 0
-}
 install(){
 local apt=""
 local apk=""
@@ -2646,6 +2649,12 @@ test -z "$apk"||sudo apk add $apk
 for file in $reload;do
 source $file
 done
+}
+installed(){
+for cmd in "$@";do
+command -v "$cmd" >/dev/null||return 1
+done
+return 0
 }
 semver(){
 input "$@"|sed -e 's#[^0-9]*\([0-9]*:\)\?\([0-9]*\)\([.]\([0-9]*\)\)\?\([.]\([0-9]*\)\)\?\(-\([^+]*\)\)\?+\?\(.*\)\?.*#\2\n\4\n\6\n\8\n\9#'
@@ -2739,5 +2748,71 @@ else
 echo "$num"
 fi
 ((num==0))&&return 0||return 1
+}
+_load_module module/software
+tsv2table(){
+install mlr
+input "$@"|mlr --csvlite --ifs '\t' -o pprint cat
+}
+tsv2md(){
+install mlr
+input "$@"|uncolorize|mlr --csvlite --ifs '\t' --omd cat
+}
+csv(){
+case $cmd in
+to)local format=$3
+case $format in
+tsv)python3 -c '
+                import sys, csv
+                reader = csv.reader(sys.stdin)
+                writer = csv.writer(sys.stdout, delimiter="\t", lineterminator="\n")
+                for row in reader:
+                    writer.writerow(row)
+                '
+;;
+*)die "Allowed formats are only tsv, not [$format]"
+esac
+;;
+*)die "Usage: table <array_name> {to|crop} [<value>]"
+esac
+}
+tsv(){
+local separator=$'\t'
+local input
+input=$(cat)
+local cmd="$1"
+case $cmd in
+to)local format=$3
+case $format in
+csv)awk 'BEGIN { FS="\t"; OFS="," }
+                {
+                    for(i=1; i<=NF; i++) {
+                        if ($i ~ /,|"|\n/) {
+                            gsub(/"/, "\"\"", $i)  # double quotes inside field
+                            $i = "\"" $i "\""
+                        }
+                    }
+                    print
+                }' <<<"$input"
+;;
+pprint)column -t -s $'\t' <<<"$input"|less -S
+;;
+*)die "Allowed formats are only csv, not [$format]"
+esac
+;;
+crop)local cols idx line orig
+IFS=$separator read -r -a cols < <(head -n 1 <<<"$input")
+is_number "$2"&&idx="$2"||idx="$(array cols indexof "$2")"||die "Column [$2] not found in table"
+local width="$3"
+[[ -n $col && -n $width ]]||die "Usage: table crop <column> <width>"
+while IFS=$separator read -r -a line;do
+orig="${line[idx]}"
+((${#orig}<=width))||line[idx]="${orig:0:width-1}…"
+(IFS="$separator"
+echo "${line[*]}")
+done <<<"$input"
+;;
+*)die "Usage: table <array_name> {to|crop} [<value>]"
+esac
 }
 source $BASHLIB_HOME/configs
