closes #91 new tsv handling

diff --git a/remote b/remote
--- a/remote
+++ b/remote
@@ -1151,7 +1151,18 @@ is set -npage-id -d -- "$1"
 install jq
 curl -H "Content-Type: application/json" -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" "$CONFLUENCE_API/content/$1?expand=body.storage"|jq .body.storage.value -r||die "Could not read confluence page!"
 }
+JIRA_HTTP_CODE=""
+JIRA_ERROR=""
 jira(){
+local noDie
+eval set -- "$(option_parse $'- no-die -' "$@")"
+while true;do
+case "$1" in
+--no-die)noDie=1&&shift;;
+--)shift&&break;;
+*)die "$(gettext "Unrecognized option"): $1"
+esac
+done
 is set -nJIRA_HOST -d -- "$JIRA_HOST"
 is set -nATLASSIAN_USER -d -- "$ATLASSIAN_USER"
 is set -nATLASSIAN_TOKEN -d -- "$ATLASSIAN_TOKEN"
@@ -1160,39 +1171,39 @@ case "$command" in
 get)is set -narguments --max=1 -d $#
 is set -nissueId-or-key -d -- "$1"
 debug "GET issue $1"
-_jira GET "issue/$1"
+_jira GET "issue/$1" "" $noDie
 ;;
 search)is set -narguments --max=1 -d $#
 is set -njql -d -- "$1"
 debug "SEARCH issue $1"
 local res rc=0
-_jira GET "search/jql?jql=$(urlencode "$1")"|jq .issues[].id -r
+_jira GET "search/jql?jql=$(urlencode "$1")" "" $noDie|jq .issues[].id -r
 ;;
 create)is set -narguments --max=1 -d $#
 is set -njson -d -- "$1"
 debug "CREATE issue ${jq-r '.fields.summary' <<<"$1"}"
-_jira POST issue "$1"|jq .id -r
+_jira POST issue "$1" $noDie|jq .id -r
 ;;
 update)is set -narguments --max=2 -d $#
 is set -nissueId-or-key -d -- "$1"
 is set -njson -d -- "$2"
 debug "UPDATE issue $1"
-_jira PUT "issue/$1" "$2" >/dev/null
+_jira PUT "issue/$1" "$2" $noDie >/dev/null
 ;;
 delete)is set -narguments --max=1 -d $#
 is set -nissueId-or-key -d -- "$1"
 debug "DELETE issue $1"
-_jira GET "issue/$1"
+_jira GET "issue/$1" "" $noDie
 ;;
 project)is set -narguments --max=1 -d $#
 is set -nprojectId-or-key -d -- "$1"
 debug "GET project $1"
-_jira GET "project/$1"
+_jira GET "project/$1" "" $noDie
 ;;
 fields)is set -narguments --max=2 -d $#
 is set -nprojectId-or-key -d -- "$1"
 is set -nissueTypeId -d -- "$2"
-debug "GET fields $1/$2"
+debug "GET fields $1/$2" "" $noDie
 _jira GET "issue/createmeta/$1/issuetypes/$2"
 ;;
 json)local empty='{"fields":{}}' var="$1"
@@ -1494,24 +1505,35 @@ _jira(){
 local METHOD=$1
 local REST="$2"
 local DATA="$3"
+local noDie=$4
 local api=rest/api/3
-local res rc=0 num=0 retry=3
+local res rc=0 num=0 retry=5
 while ((num<=retry));do
 ((num==0))||debug "Retry $num"
 res="$(curl --store $$ --request "$METHOD" --url "$JIRA_HOST/$api/$REST" --user "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" --data "$DATA" -H "Content-Type: application/json")"||rc=$?
+JIRA_HTTP_CODE=$CURL_HTTP_CODE
 variables restore --clean $$
-if ((rc==0));then
+if ((rc==0))&&[[ ! $CURL_HTTP_CODE =~ ^2[0-9]{2}$ ]];then
 printf '%s' "$res"
 return
 else
+JIRA_ERROR="$(printf "HTTP Code $CURL_HTTP_CODE: ($rc) "&&jq .errorMessages[] -r <<<"$res"||printf '%s' "$res")"
+if [ -n "$noDie" ];then
+return 1
+else
 case $CURL_HTTP_CODE in
-400|404)(printf "HTTP Code $CURL_HTTP_CODE: ($rc) "&&jq .errorMessages[] -r <<<"$res"||printf '%s' "$res")|die
+400|404)echo "$JIRA_ERROR"|die
 esac
+fi
 fi
 ((num++))||true
 sleep $(((num+1)**2))
 done
-(printf "HTTP Code $CURL_HTTP_CODE: "&&jq .errorMessages[] -r <<<"$res"||printf '%s' "$res")|die
+if [ -n "$noDie" ];then
+return 1
+else
+echo "$JIRA_ERROR"|die
+fi
 }
 COMPRESSION_DEFAULT=${COMPRESSION_DEFAULT:-gzip}
 compress(){
@@ -4098,165 +4120,190 @@ esac
 esac
 }
 use software
-sv(){
-local opt=() QSV_DEFAULT_DELIMITER
-eval set -- "$(option_parse $'d delimiter +' "$@")"
+tsv(){
+local opt=(-d $'\t') opt2=() QSV_DEFAULT_DELIMITER=$'\t' noHeaders input output sort literal exact invert flag numerical natural reverse ignoreCase unique maxWidth schema table drop
+eval set -- "$(option_parse $'- no-headers -\ni input-file +\no output-file +\ns sort -\n- max-col-width +\n- schema +\n-table +\n- drop -' "$@")"
 while true;do
 case "$1" in
--d|--delimiter)is set -ndelimiter -d -- "$2"&&QSV_DEFAULT_DELIMITER="$2"&&opt+=(-d "$2")&&shift 2;;
---no-headers)opt+=(-n)&&shift;;
+--no-headers)noHeaders=1&&shift;;
+-i|--input-file)is readable -ninput-file -doinput -- "$2"&&shift 2;;
+-o|--output-file)is set -noutput-file -dooutput -- "$2"&&shift 2;;
+-s|--sort)sort=1&&shift;;
+--max-col-width)is integer -nmax-col-width --min=5 -domaxWidth -- "$2"&&shift 2;;
+--literal)literal=1&&shift;;
+--exact)exact=1&&shift;;
+--invert)invert=1&&shift;;
+--flag)is set -nflag-column -doflag -- "$2"&&shift 2;;
+--numeric)numeric=1&&shift;;
+--natural)natural=1&&shift;;
+--reverse)reverse=1&&shift;;
+--ignore-case)ignoreCase=1&&shift;;
+--unique)unique=1&&shift;;
+--schema)is set -nschema -doschema -- "$2"&&shift 2;;
+--table)is set -ntable -dotable -- "$2"&&shift 2;;
+--drop)drop=1&&shift;;
 --)shift&&break;;
 *)die "$(gettext "Unrecognized option"): $1"
 esac
 done
-is enum -ncommand --allow="headers count select" -docmd -- "$1"
+is enum -ncommand --allow="headers count select filter slice sort reverse edit crop print to" -docmd -- "$1"
 install qsv
 case $cmd in
-headers)qsv headers "${opt[@]}";;
-count)qsv count "${opt[@]}";;
-select)qsv select "${opt[@]}" 1
-esac
-}
-esv2(){
-local opt=()
-eval set -- "$(option_parse $'d delimiter +' "$@")"
-while true;do
-case "$1" in
--d|--delimiter)is set -ndelimiter -d -- "$2"&&opt+=(-d "$2")&&shift 2;;
---no-headers)opt+=(-n)&&shift;;
---)shift&&break;;
-*)die "$(gettext "Unrecognized option"): $1"
-esac
-done
-is enum -ncommand --allow="headers count" -docmd -- "$1"
-install ebay-tsv-utils
-case $cmd in
-headers)qsv headers "${opt[@]}";;
-count)qsv count "${opt[@]}"
-esac
-}
-tsv(){
-local withHeader removeHeader cmd unique
-eval set -- "$(option_parse $'- with-header -\n- remove-header -' "$@")"
-while true;do
-case "$1" in
---with-header)withHeader=1&&shift;;
---remove-header)removeHeader=1&&shift;;
---unique)unique=1&&shift;;
---)shift&&break;;
-*)die "$(gettext "Unrecognized option"): $1"
-esac
-done
-is enum -ncommand --allow="crop sort reverse to filter" -docmd -- "$1"
-local separator=$'\t' input
-input=$(cat)
-is false -- "$removeHeader"||removeHeader="${removeHeader#*$'\n'}"
-case $cmd in
-filter)local header cols idx line
-if is true -- "$withHeader";then
-header="$(head -1 <<<"$input")"
-echo "$header"
-input="$(tail -n +2 <<<"$input")"
-fi
-if (($#>=2));then
-is set -ntype -d -- "$2"
-is set -nnum-name -d -- "$3"
-is set -noperator -d -- "$4"
-is set -ncompare -d -- "$5"
-is integer -narguments --min=4 --max=5 -d $#
-IFS=$'\t' read -r -a cols <<<"$header"
-if [[ "$3" =~ ^-?[0-9]+$ ]];then
-idx=$(($3-1))
-else
-[ -n "$header" ]||die "Named columns only possible using --with-header option"
-idx="$(array cols indexof "$3")"||die "Column [$3] not found in table"
-fi
-debug "filter $2 cols[$idx] $4 $5"
-while IFS= read -r line;do
-IFS=$'\t' read -r -a cols <<<"$line"
-debug "check $2 $idx:\"${cols[idx]}\" \"$4\" \"$5\""
-check $2 "${cols[idx]}" "$4" "$5"||continue
-echo "$line"
-done <<<"$input"
-else
-printf '%s' "$input"
-fi
+headers)is integer -narguments --max=1 -d $#
+qsv headers "${opt[@]}"
 ;;
-to)is enum -nformat --allow="csv pprint" -d -- "$2"
+count)[ -z "$noHeaders" ]||opt+=(-n)
+[ -z "$input" ]||opt+=("$input")
+is integer -narguments --max=1 -d $#
+qsv count "${opt[@]}"
+;;
+select)[ -z "$noHeaders" ]||opt+=(-n)
+[ -z "$output" ]||opt+=(-o "$output")
+[ -z "$sort" ]||opt+=(-S)
+[ -z "$input" ]||opt+=("$input")
+is set -nselection -d -- "$2"
 is integer -narguments --max=2 -d $#
-local format=$2
-case $format in
-csv)awk '
-BEGIN { FS="\t"; OFS="," }
-{
-for(i=1; i<=NF; i++) {
-if ($i ~ /,|"|\n/) {
-gsub(/"/, "\"\"", $i)
-$i = "\"" $i "\""
-}
-}
-$1 = $1
-print
-}
-' <<<"$input"
+qsv select "${opt[@]}" "$2"
 ;;
-pprint)input="$(column -t -s $'\t' <<<"$input")"
-if is true -- "$withHeader";then
-echo "$CC_INVERS${input%%$'\n'*}$CC_RESET"
-input="${input#*$'\n'}"
-fi
-echo "$input"
+filter)[ -z "$noHeaders" ]||opt+=(-n)
+[ -z "$literal" ]||opt+=(--literal)
+[ -z "$exact" ]||opt+=(--exact)
+[ -z "$invert" ]||opt+=(-v)
+[ -z "$flag" ]||opt+=(-f "$flag")
+[ -z "$3" ]||opt+=(-s "$3")
+[ -z "$ignoreCase" ]||opt+=(-i)
+is set -nregex -d -- "$2"&&opt+=("$2")
+[ -z "$input" ]||opt+=("$input")
+[ -z "$output" ]||opt2+=(-o "$output")
+is integer -narguments --max=3 -d $#
+qsv search "${opt[@]}" --not-one|qsv fmt "${opt2[@]}" -t '\t'
 ;;
-*)die "Allowed formats are only csv, not [$format]"
-esac
+slice)[ -z "$noHeaders" ]||opt+=(-n)
+[ -z "$invert" ]||opt+=(--invert)
+[ -z "$2" ]||opt+=(-s "$2")
+[ -z "$3" ]||opt+=(-e "$3")
+[ -z "$input" ]||opt+=("$input")
+[ -z "$output" ]||opt2+=(-o "$output")
+is integer -narguments --max=3 -d $#
+qsv slice "${opt[@]}"|qsv fmt "${opt2[@]}" -t '\t'
 ;;
-crop)is set -nnum-name -- "$2"
+sort)[ -z "$noHeaders" ]||opt+=(-n)
+[ -z "$2" ]||opt+=(-s "$2")
+[ -z "$numeric" ]||opt+=(-N)
+[ -z "$natural" ]||opt+=(--natural)
+[ -z "$reverse" ]||opt+=(-R)
+[ -z "$ignoreCase" ]||opt+=(-i)
+[ -z "$unique" ]||opt+=(-u)
+[ -z "$input" ]||opt+=("$input")
+[ -z "$output" ]||opt2+=(-o "$output")
+is integer -narguments --max=2 -d $#
+qsv sort "${opt[@]}"|qsv fmt "${opt2[@]}" -t '\t'
+;;
+reverse)[ -z "$noHeaders" ]||opt+=(-n)
+[ -z "$output" ]||opt+=(-o "$output")
+[ -z "$input" ]||opt+=("$input")
+qsv reverse "${opt[@]}"|qsv fmt -t '\t'
+;;
+edit)[ -z "$noHeaders" ]||opt+=(-n)
+[ -z "$noHeaders" ]||opt2+=(-n)
+is integer -narguments --min=4 --max=4 -d $#
+qsv fmt "${opt[@]}"|qsv edit "${opt2[@]}" - "$2" "$3" "$4"|qsv fmt -t '\t'
+;;
+crop)is set -ncolumn -d -- "$2"
 is integer -nwidth --min=3 -d -- "$3"
-is integer -narguments --max=4 -d $#
-local cols idx
-IFS=$separator read -r -a cols < <(head -n 1 <<<"$input")
-[[ "$2" =~ ^-?[0-9]+$ ]]&&idx=$(($2-1))||idx="$(array cols indexof "$2")"||die "Column [$2] not found in table"
-local width="$3"
-[[ -n $idx && -n $width ]]||die "Usage: table crop <column> <width>"
-local line orig
-while IFS=$separator read -r -a line;do
-orig="${line[idx]}"
-((${#orig}<=width))||line[idx]="${orig:0:width-1}…"
-(IFS="$separator"
-printf '%s\n' "${line[*]}")
-done <<<"$input"
+cat "${input:-/dev/stdin}"|if [[ "$2" =~ ^-?[0-9]+$ ]];then
+awk -F $'\t' -v OFS=$'\t' -v col="$2" -v width="$3" '
+                    BEGIN { col_idx = col + 0 }  # Convert to 0-based index
+                    NR==1 { print; next }        # Pass header unchanged
+                    NF>0 {
+                        if (length($col_idx) > width) {
+                            $col_idx = substr($col_idx, 1, width-1) "…"
+                        }
+                        print
+                    }'
+else
+awk -F $'\t' -v OFS=$'\t' -v colname="$2" -v width="$3" '
+                    NR==1 {
+                        for(i=1; i<=NF; i++) if($i == colname) { col_idx=i; break }
+                        print; next
+                    }
+                    NF>0 {                      # ← Skip empty lines
+                        if (length($col_idx) > width) {
+                            $col_idx = substr($col_idx, 1, width-1) "…"
+                        }
+                        print
+                    }'
+fi >"${output:-/dev/stdout}"
 ;;
-sort)is set -nnum-name -- "$2"
-[ -z "$3" ]||is enum -nformat --allow="numeric human" -d -- "$3"
-is integer -narguments --max=4 -d $#
-local cols idx
-IFS=$separator read -r -a cols < <(head -n 1 <<<"$input")
-[[ "$2" =~ ^-?[0-9]+$ ]]&&idx=$(($2-1))||idx="$(array cols indexof "$2")"||die "Column [$2] not found in table"
-local col type
-col=$((idx+1))
-case "$3" in
-numeric)type=n;;
-human)type=h
+print)[ -z "$output" ]||opt+=(-o "$output")
+[ -z "$maxWidth" ]||opt+=(-c $((maxWidth-3)))
+[ -z "$input" ]||opt+=("$input")
+is integer -narguments --max=1 -d $#
+qsv color "${opt[@]}"
+;;
+to)is enum -nformat --allow="csv postgres sqlite xslx ods json" -d -- "$2"
+local temp
+case $2 in
+csv)[ -z "$output" ]||opt+=(-o "$output")
+[ -z "$input" ]||opt+=("$input")
+is integer -narguments --max=2 -d $#
+qsv fmt -t ',' "${opt[@]}"
+;;
+json)[ -z "$output" ]||opt+=(-o "$output")
+[ -z "$input" ]||opt+=("$input")
+is integer -narguments --max=2 -d $#
+qsv tojsonl "${opt[@]}"
+;;
+postgres)is set ---name=table -d -- "$table"
+is integer -narguments --max=3 -d $#
+temp="$(mktemp -d $$)"
+if [ -n "$input" ];then
+cp "$input" "$temp/$table.tsv"
+else
+cat >"$temp/$table.tsv"
+fi
+if [ -n "$3" ];then
+[ -z "$schema" ]||opt+=(--schema "$schema")
+is false -- "$drop"||opt+=(--drop)
+opt+=("$3")
+elif [ -n "$output" ];then
+opt+=(--dump "$output")
+else
+opt+=(--dump -)
+fi
+qsv to postgres "${opt[@]}" "$temp/$table.tsv"
+rm -rf "$temp"
+;;
+sqlite)is set ---name=table -d -- "$table"
+is integer -narguments --max=3 -d $#
+temp="$(mktemp -d $$)"
+if [ -n "$input" ];then
+cp "$input" "$temp/$table.tsv"
+else
+cat >"$temp/$table.tsv"
+fi
+if [ -n "$3" ];then
+[ -z "$schema" ]||opt+=(--schema "$schema")
+is false -- "$drop"||opt+=(--drop)
+opt+=("$3")
+elif [ -n "$output" ];then
+opt+=(--dump "$output")
+else
+opt+=(--dump -)
+fi
+qsv to sqlite "${opt[@]}" "$temp/$table.tsv"
+rm -rf "$temp"
+;;
+xlsx|ods)[ -n "$input" ]||opt+=(--pipe)
+[ -z "$output" ]||opt+=("$output")
+is integer -narguments --max=2 -d $#
+if [ -n "$input" ];then
+opt+=("$input")
+else
+opt+=("-")
+fi
+qsv to $2 "${opt[@]}"
 esac
-[ -z "$unique" ]||type+=u
-[[ -n $idx ]]||die "Usage: table sort <column> [numeric/human]"
-if is true -- "$withHeader";then
-(IFS="$separator"
-printf '%s\n' "${cols[*]}")
-tail -n +2 <<<"$input"|sort -t $'\t' "-k$col,$col$type"
-else
-sort -t $'\t' "-k$col,$col$type" <<<"$input"
-fi
-;;
-reverse)is integer -narguments --max=1 -d $#
-if is true -- "$withHeader";then
-head -1 <<<"$input"
-tail -n +2 <<<"$input"|tac
-else
-tac <<<"$input"
-fi
-;;
-*)die "Usage: tsv {to|crop} [<value>]"
 esac
 }
 TRIVY_DEFAULT_TIMEOUT=${TRIVY_DEFAULT_TIMEOUT:-60m}
@@ -4335,6 +4382,7 @@ mkdir -p "$_trivy_cache/jira"
 ! is file -- "$_trivy_cache/exploits.json"||find "$_trivy_cache/exploits.json" -mmin +1440 -delete
 is file -- "$_trivy_cache/exploits.json"||curl -s "$TRIVY_EXPLOITS_URL" -o "$_trivy_cache/exploits.json"
 local project
+if [ -n "$TRIVY_JIRA_BOARD" ];then
 project="$(jira project "$TRIVY_JIRA_BOARD")"
 _trivy_jira[board]="$(jq .id -r <<<"$project")"
 [ -n "${_trivy_jira[board]}" ]||die "Could not find JIRA Board ID for $TRIVY_JIRA_BOARD!"
@@ -4351,6 +4399,7 @@ _trivy_jira[field_links]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD
 [ -n "${_trivy_jira[field_links]}" ]||die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_LINKS\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
 _trivy_jira[field_approval]="$(jq '.fields[] | select(.name == "'"$TRIVY_JIRA_FIELD_APPROVAL"'").key' -r <<<"$fields")"
 [ -n "${_trivy_jira[field_approval]}" ]||die "Could not find JIRA Field \"$TRIVY_JIRA_FIELD_APPROVAL\" in $TRIVY_JIRA_BOARD/$TRIVY_JIRA_ISSUE_TYPE!"
+fi
 [ -z "$progress" ]||gettext 'Build queue to optimize reports...'|info >&2
 for file in "$work"/split/*;do
 queue add _trivy_report "$work" "$file" "$source" "$progress"
