reformat docs

diff --git a/module/atlassian b/module/atlassian
--- a/module/atlassian
+++ b/module/atlassian
@@ -13,16 +13,17 @@ source /dev/null
 ######################################################################################
 
 # Get page content from Confluence using API
+#
 # Usage:    confluence <page_id>
 # Output:   <html>
 confluence() {
-    is integer --name=arguments --max=1 --die -- $#
-    is set --name=page-id --die -- "$1"
-    # processing
-    install jq
-    curl -H "Content-Type: application/json" -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" "$CONFLUENCE_API/content/$1?expand=body.storage" |
-        jq .body.storage.value -r ||
-        die "Could not read confluence page!"
+  is integer --name=arguments --max=1 --die -- $#
+  is set --name=page-id --die -- "$1"
+  # processing
+  install jq
+  curl -H "Content-Type: application/json" -u "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" "$CONFLUENCE_API/content/$1?expand=body.storage" |
+    jq .body.storage.value -r ||
+    die "Could not read confluence page!"
 }
 
 ######################################################################################
@@ -35,6 +36,7 @@ confluence() {
 # https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-group-issues
 
 # Jira API calls
+#
 # To connect the $ATLASSIAN_USER and $ATLASSIAN_TOKEN is needed.
 # Jira API V3 is used there: https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro which brings some elements in the [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/).
 #
@@ -48,78 +50,90 @@ confluence() {
 #
 # The Jira JSON consists of the `fields` array and some additional meta like `id`, `key`. To simplify work with it the json helper allows to manipulate it.
 #
-# Usage:    jira <command> <options>...
-#           jira get <issueId>|<key>
-#           jira search <jql>
-#           jira update <ticket-id> <json>
-#           jira create <json>
-#           jira delete <issueId>|<key>
-#           jira project <key>
+# Usage:    jira get <issueId>|<key>                      # get an jira issue
+#           jira search <jql>                             # search jira issue id
+#           jira update <ticket-id> <json>                # update jira issue
+#           jira create <json>                            # create new jira issue
+#           jira delete <issueId>|<key>                   # delete jira issue
+#           jira project <key>                            # get project information
+#           jira fields <projectId>|<key> <issueTypeId>   # get fields by project and issue type
+#           # work with the issue json:
 #           jira json <json> set <field> <value>
 #           jira json <json> get <field>
 #           jira json <json> remove <field>
+#           # convert atlassian document format:
 #           jira adf parse <json>
 #           jira adf format <md>
+# Global:   $JIRA_HOST
+#           $ATLASSIAN_USER
+#           $ATLASSIAN_TOKEN
 # Output:   - get: <json>
 #           - search: <issueId> list, each in a separate line
 #           - create: <issueId> which was just created
 # Return:   die on 400, 404 Error
 #           retry on other not 2xx Code
 jira() {
-    is set --name=JIRA_HOST --die -- "$JIRA_HOST"
-    is set --name=ATLASSIAN_USER --die -- "$ATLASSIAN_USER"
-    is set --name=ATLASSIAN_TOKEN --die -- "$ATLASSIAN_TOKEN"
-    is enum --name=command --allow="get search create delete project json adf" --die -- "$1" && local command="$1" && shift
-    # processing
-    case "$command" in
-    get)
-        is set --name=arguments --max=1 --die -- $#
-        is set --name=issueId-or-key --die -- "$1"
-        debug "GET $1"
-        _jira GET "issue/$1"
-        ;;
-    search)
-        is set --name=arguments --max=1 --die -- $#
-        is set --name=jql --die -- "$1"
-        debug "SEARCH $1"
-        local res rc=0
-        _jira GET "search/jql?jql=$(urlencode "$1")" | jq .issues[].id -r
-        ;;
-    create)
-        is set --name=arguments --max=1 --die -- $#
-        is set --name=json --die -- "$1"
-        debug "CREATE Issue ${jq-r '.fields.summary' <<<"$1"}"
-        _jira POST issue "$1" | jq .id
-        ;;
-    delete)
-        is set --name=arguments --max=1 --die -- $#
-        is set --name=issueId-or-key --die -- "$1"
-        debug "DELETE $1"
-        _jira GET "issue/$1"
-        ;;
-    project)
-        is set --name=arguments --max=1 --die -- $#
-        is set --name=projectId-or-key --die -- "$1"
-        debug "GET $1"
-        _jira GET "project/$1"
-        ;;
-    json)
-        local empty='{"fields":{}}'
-        local json="${1:-$empty}" && shift
-        is enum --name=sub-command --allow="set get remove" --die -- "$1" && local subCommand="$1" && shift
-        is set --name=field --die -- "$1" && local field="$1"
-        case "$subCommand" in
-        set) jq --arg v "$2" ".fields.$field = \$v" <<<"$json" ;;
-        get) jq ".fields.$field" <<<"$json" ;;
-        remove) jq "del(.fields.$field)" <<<"$json" ;;
-        esac
-        ;;
-    adf)
-        is enum --name=sub-command --allow="parse format" --die -- "$1" && local subCommand="$1" && shift
-        case "$subCommand" in
-        parse)
-            is set --name=json --die -- "$1" && local json="$1"
-            jq -r '
+  is set --name=JIRA_HOST --die -- "$JIRA_HOST"
+  is set --name=ATLASSIAN_USER --die -- "$ATLASSIAN_USER"
+  is set --name=ATLASSIAN_TOKEN --die -- "$ATLASSIAN_TOKEN"
+  is enum --name=command --allow="get search create delete project fields json adf" --die -- "$1" && local command="$1" && shift
+  # processing
+  case "$command" in
+  get)
+    is set --name=arguments --max=1 --die -- $#
+    is set --name=issueId-or-key --die -- "$1"
+    debug "GET $1"
+    _jira GET "issue/$1"
+    ;;
+  search)
+    is set --name=arguments --max=1 --die -- $#
+    is set --name=jql --die -- "$1"
+    debug "SEARCH $1"
+    local res rc=0
+    _jira GET "search/jql?jql=$(urlencode "$1")" | jq .issues[].id -r
+    ;;
+  create)
+    is set --name=arguments --max=1 --die -- $#
+    is set --name=json --die -- "$1"
+    debug "CREATE Issue ${jq-r '.fields.summary' <<<"$1"}"
+    _jira POST issue "$1" | jq .id
+    ;;
+  delete)
+    is set --name=arguments --max=1 --die -- $#
+    is set --name=issueId-or-key --die -- "$1"
+    debug "DELETE $1"
+    _jira GET "issue/$1"
+    ;;
+  project)
+    is set --name=arguments --max=1 --die -- $#
+    is set --name=projectId-or-key --die -- "$1"
+    debug "GET $1"
+    _jira GET "project/$1"
+    ;;
+  fields)
+    is set --name=arguments --max=2 --die -- $#
+    is set --name=projectId-or-key --die -- "$1"
+    is set --name=issueTypeId --die -- "$2"
+    debug "GET $1"
+    _jira GET "issue/createmeta/$1/issuetypes/$2"
+    ;;
+  json)
+    local empty='{"fields":{}}'
+    local json="${1:-$empty}" && shift
+    is enum --name=sub-command --allow="set get remove" --die -- "$1" && local subCommand="$1" && shift
+    is set --name=field --die -- "$1" && local field="$1"
+    case "$subCommand" in
+    set) jq --arg v "$2" ".fields.$field = \$v" <<<"$json" ;;
+    get) jq ".fields.$field" <<<"$json" ;;
+    remove) jq "del(.fields.$field)" <<<"$json" ;;
+    esac
+    ;;
+  adf)
+    is enum --name=sub-command --allow="parse format" --die -- "$1" && local subCommand="$1" && shift
+    case "$subCommand" in
+    parse)
+      is set --name=json --die -- "$1" && local json="$1"
+      jq -r '
     def para(p):
       p.content[]?.text // "";
 
@@ -153,10 +167,10 @@ jira() {
     s/<em>(.+?)<\/em>/*\1*/g
     s/<code>(.+?)<\/code>/`\1`/g
   '
-            ;;
-        format)
-            is set --name=text --die -- "$1"
-            jq -n --arg text "$text" '
+      ;;
+    format)
+      is set --name=text --die -- "$1"
+      jq -n --arg text "$text" '
     def paragraph(t):
       { type: "paragraph", content: [{ type: "text", text: t }] };
 
@@ -263,34 +277,34 @@ jira() {
     s/\*(.+?)\*/<em>\1<\/em>/g
     s/`([^`]+)`/<code>\1<\/code>/g
   '
-            ;;
-        esac
-        ;;
+      ;;
     esac
+    ;;
+  esac
 }
 
 # Usage _jira <method> <path> <data>
 _jira() {
-    local METHOD=$1
-    local REST="$2"
-    local DATA="$3"
-    local api=/rest/api/3
-    local res rc=0 num=0 retry=3
-    while ((num <= retry)); do
-        ((num == 0)) || debug "Retry $num"
-        res="$(curl --store --request "$METHOD" --url "$JIRA_HOST/$api/$REST" --user "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" --data "$DATA" -H "Content-Type: application/json")" || rc=$?
-        variables restore --clean curl
-        if ((rc == 0)); then
-            echo "$res"
-            return
-        else
-            # error code handling without retry
-            case $CURL_HTTP_CODE in
-            400 | 404) (echo -n "HTTP Code $CURL_HTTP_CODE: " && jq .errorMessages[] -r <<<"$res" || echo "$res") | die ;;
-            esac
-        fi
-        ((num++)) || true
-        sleep $(((num + 1) ** 2))
-    done
-    (echo -n "HTTP Code $CURL_HTTP_CODE: " && jq .errorMessages[] -r <<<"$res" || echo "$res") | die
+  local METHOD=$1
+  local REST="$2"
+  local DATA="$3"
+  local api=/rest/api/3
+  local res rc=0 num=0 retry=3
+  while ((num <= retry)); do
+    ((num == 0)) || debug "Retry $num"
+    res="$(curl --store --request "$METHOD" --url "$JIRA_HOST/$api/$REST" --user "$ATLASSIAN_USER:$ATLASSIAN_TOKEN" --data "$DATA" -H "Content-Type: application/json")" || rc=$?
+    variables restore --clean curl
+    if ((rc == 0)); then
+      echo "$res"
+      return
+    else
+      # error code handling without retry
+      case $CURL_HTTP_CODE in
+      400 | 404) (echo -n "HTTP Code $CURL_HTTP_CODE: " && jq .errorMessages[] -r <<<"$res" || echo "$res") | die ;;
+      esac
+    fi
+    ((num++)) || true
+    sleep $(((num + 1) ** 2))
+  done
+  (echo -n "HTTP Code $CURL_HTTP_CODE: " && jq .errorMessages[] -r <<<"$res" || echo "$res") | die
 }
