fix lint problems

diff --git a/module/monitoring b/module/monitoring
--- a/module/monitoring
+++ b/module/monitoring
@@ -1,9 +1,15 @@
 #!/usr/bin/env bash
+# shellcheck source=base
+source /dev/null
+# shellcheck source=config/environment
+source /dev/null
+# shellcheck source=config/secrets
+source /dev/null
 
 # Using the Grafana/Prometheus APIs to get Monitoring information.
 
 # load other modules if not already done
-declare -F "curl" >/dev/null || source $BASHLIB_HOME/module/remote
+declare -F "curl" >/dev/null || source "$BASHLIB_HOME"/module/remote
 
 ######################################################################################
 # Monitoring
@@ -18,9 +24,8 @@ exporter() {
     local arg name value
     local filter=""
     for arg in "$@"; do
-        IFS='=' read name value <<<"$arg"
+        IFS='=' read -r name value <<<"$arg"
         unset IFS
-        local field=""
         case $name in
         instance) filter="$filter select(.labels.$name|test(\"$value\")) |" ;;
         *) filter="$filter select(.labels.$name==\"$value\") |" ;;
@@ -30,16 +35,24 @@ exporter() {
     local auth=""
     for server in $PROMETHEUS; do
         remote true 2>/dev/null || continue
+        # shellcheck disable=SC2016
         auth="$auth"$'\n'"$(remote cat /etc/prometheus/prometheus.yml |
-            yq -r '.scrape_configs[] | select(.basic_auth) | .job_name as $j | .basic_auth as $b | .static_configs[].targets[] | [$j, $b.username, $b.password, .] | @tsv')"
+            yq -r '.scrape_configs[] 
+            | select(.basic_auth) 
+            | .job_name as $j 
+            | .basic_auth as $b 
+            | .static_configs[].targets[] 
+            | [$j, $b.username, $b.password, .] 
+            | @tsv')"
     done
     for api in $PROMETHEUS_API; do
-        curl $api/targets | jq '.data.activeTargets[] | '"$filter"' [.scrapeUrl, .labels.job, (.labels | join(", ")), .discoveredLabels.__address__] | @tsv' -r |
-            while read line; do
-                local login="$(echo "$auth" | grep "$(echo "$line" | cut -f2)" | grep "$(echo "$line" | cut -f4)")"
+        curl "$api"/targets | jq '.data.activeTargets[] | '"$filter"' [.scrapeUrl, .labels.job, (.labels | join(", ")), .discoveredLabels.__address__] | @tsv' -r |
+            while read -r line; do
+                local login user pass
+                login="$(echo "$auth" | grep "$(echo "$line" | cut -f2)" | grep "$(echo "$line" | cut -f4)")"
                 if [ -n "$login" ]; then
-                    local user="$(echo "$login" | cut -f2 | tr -d '\n' | urlencode)"
-                    local pass="$(echo "$login" | cut -f3 | tr -d '\n' | urlencode)"
+                    user="$(echo "$login" | cut -f2 | tr -d '\n' | urlencode)"
+                    pass="$(echo "$login" | cut -f3 | tr -d '\n' | urlencode)"
                     echo "$line" | cut -f1-3 | sed "s#://#://$user:$pass@#"
                 else
                     echo "$line" | cut -f1-3
@@ -56,7 +69,8 @@ exporter() {
 scrape() {
     num_parameters "$@" --min 1 --max 2 --die "Wrong number of parameters for scrape!"
     echo "Scrape the prometheus exporter at $1" >&2
-    local metrics="$(curl "$1" | egrep "$2" | egrep -v '^($|#)' || die "Could not scrape the prometheus exporter at $1!")"
+    local metrics
+    metrics="$(curl "$1" | grep -E "$2" | grep -Ev '^($|#)' || die "Could not scrape the prometheus exporter at $1!")"
     echo "$metrics" | grep '{' | sed 's/,\?[{}]/\t/g'
     echo "$metrics" | grep -v '{' | sed 's/ /\t\t/g'
 }
@@ -86,7 +100,8 @@ alerts() {
     done
     # processing
     install jq mlr
-    local alerts="$(curl -H "Authorization: Bearer $GRAFANA_TOKEN" "$GRAFANA_API/alertmanager/grafana/api/v2/alerts" |
+    local alerts
+    alerts="$(curl -H "Authorization: Bearer $GRAFANA_TOKEN" "$GRAFANA_API/alertmanager/grafana/api/v2/alerts" |
         jq 'sort_by(.startsAt) | .[] '"$filter")" ||
         die "Could not get alerts from Grafana!"
     local format=${1:-console}
@@ -139,7 +154,8 @@ alerts() {
 # Prom ql ausführen
 # Usage:    prometheus <prom-ql>
 prometheus() {
-    local api=$(echo "$PROMETHEUS_API" | sed 's/ .*//')
+    local api
+    api="${PROMETHEUS_API%% *}"
     curl "$api/query?query=$(echo "$1" | urlencode)"
     # start=
     # end=
@@ -151,7 +167,7 @@ prometheus() {
 prometheus_scrape() {
     install yq
     local job=$1
-    local seconds=${2:-60}
+    local -i seconds=${2:-60}
     for server in $PROMETHEUS; do
         remote true 2>/dev/null || continue # only work on reachable server
         echo "Let $server scrape $job again, now."
@@ -159,7 +175,7 @@ prometheus_scrape() {
         remote curl -sX POST http://localhost:9090/-/reload
     done
     echo "Wait $seconds seconds till scrape should be done..."
-    sleep $seconds
+    sleep "$seconds"
     echo "Reset config back to default."
     for server in $PROMETHEUS; do
         remote true 2>/dev/null || continue # only work on reachable server
