add log manager which will cleanup rotate on size and compress

diff --git a/module/output b/module/output
--- a/module/output
+++ b/module/output
@@ -33,7 +33,7 @@ _log_rotate_time[daily]="%Y-%m-%d"
 _log_rotate_time[weekly]="%Y_week_%W"
 _log_rotate_time[monthly]="%Y-%m"
 declare -Ag _log_active
-# _log_active[path]="<path> <level> <rotate> <cleanup>"
+# _log_active[path]="<path> <level> <rotate> [<compress> [<cleanup>]]"
 
 # Additional logging (at the moment only into files).
 # After initialising a log using `start` the default output options will additionally write into log. But you can also specifically write t it using the log function.
@@ -43,17 +43,17 @@ declare -Ag _log_active
 #           log end <file>
 # Options:  -l, --level=<level>                 # level := debug info notice warn error critical
 #           # File logging:
-#           -r, --rotate=hourly|daily|weekly|monthly
+#           -r, --rotate=hourly|daily|weekly|monthly|<bytes>
 #           -c, --cleanup=<num>|<duration>
+#           -z, --compress
 # Files:    <file>[_<pattern>]                  # will contain the logs
 # Example:  # Format: <date> <time> <level> <message>
 #           2025-12-02 14:07:35 INFO Hello
 #           2025-12-02 14:10:04 ERROR Thius is only a test
-# TODO: rotate=<bytes>
 log() {
     # parameter parsing
-    local level=1 rotate cleanup text
-    eval set -- "$(option_parse $'l level +\nr rotate +\nc cleanup +' "$@")"
+    local level=1 rotate compress=0 cleanup text size
+    eval set -- "$(option_parse $'l level +\nr rotate +\nz compress -\nc cleanup +' "$@")"
     while true; do
         case "$1" in
         -l | --level)
@@ -61,11 +61,19 @@ log() {
             shift 2
             ;;
         -r | --rotate)
-            rotate="$(hash _log_rotate_time get "$2")" || die "Rotate option $2 is not recognized use: horly daily weekly monthly"
+            if (($2 > 0)); then
+                rotate="$2"
+            else
+                rotate="$(hash _log_rotate_time get "$2")" || die "Rotate option $2 is not recognized use: horly daily weekly monthly"
+            fi
             shift 2
             ;;
+        -z | --compress)
+            compress=1
+            shift
+            ;;
         -c | --cleanup)
-            cleanup="$2"
+            cleanup="$(duration_format seconds "$2")"
             shift 2
             ;;
         --)
@@ -75,13 +83,14 @@ log() {
         *) die "$(gettext "Unrecognized option"): $1" ;;
         esac
     done
-    [ -n "$rotate" ] || cleanup="" # no cleanup if no rotate
+    [ -n "$rotate" ] || cleanup=""  # no cleanup if no rotate
+    [ -n "$rotate" ] || compress="" # no compress if no rotate
     # processing
     case $1 in
     start)
         num_parameters --min=2 --max=2 --die="To start a new log a file path is needed as argument" "$@"
         [ -w "$2" ] || [ -w "$(dirname "$2")" ] || die "Could not write/create log under $2"
-        hash _log_active set "$2" "$2 $level $rotate $cleanup"
+        hash _log_active set "$2" "$2 $level $rotate $compress $cleanup"
         ;;
     stop)
         num_parameters --min=2 --max=2 --die="To end a log it'S file path is needed as argument" "$@"
@@ -97,15 +106,55 @@ log() {
             read -r file minlevel rotate cleanup <<<"$e"
             ((level >= minlevel)) || continue
             path="$file"
-            [ -z "$rotate" ] || path+="_$(date_format "$rotate")"
+            if [ -n "$rotate" ] && ((rotate == 0)); then
+                path+="_$(date_format "$rotate")"
+            fi
             # log entry
             echo "$(date_format sql) ${1^^} $(uncolorize "$text")" >>"$path"
         done
-        # TODO: async cleanup
         ;;
     *) die "Unrecognized command $1: start, stop or any log level allowed" ;;
     esac
 }
+
+_log_manager() {
+    local parent=$PPID file minlevel rotate compress cleanup size
+    while true; do
+        for e in "${_log_active[@]}"; do
+            read -r file minlevel rotate compress cleanup <<<"$e"
+            # cleanup
+            if [ -n "$cleanup" ]; then
+                find "$(dirname "$file")" -type f -name "$(basename "$file")*" ! -newermt "$(date -d "$cleanup seconds ago")" -delete 2>/dev/null
+            fi
+            # rotate on size
+            if ((rotate > 0)); then
+                size="$(stat -c %s "$file")"
+                if ((size > rotate)); then
+                    mr -f "${file}.99"
+                    # Shift existing numbered files up
+                    for ((i = 99; i > 1; i--)); do
+                        local old="${file}.${i}"
+                        local new="${file}.$((i - 1))"
+                        [ ! -f "$old" ] || mv "$old" "$new"
+                    done
+                    # Rotate the main file to .1
+                    ! [ -f "$file" ] || mv "$file" "${file}.1"
+                fi
+            fi
+            # compress
+            if ((compress == 1)); then
+                find "$(dirname "$file")" -type f -name "$(basename "$file")*" -mmin 3600 -exec gzip --best {} \; 2>/dev/null
+            fi
+        done
+        # run manager every 5 minutes
+        for ((i = 0; i < 300; i++)); do
+            sleep 1
+            kill -0 "$parent" 2>/dev/null || exit 0 # end if parent ended
+        done
+    done
+}
+_log_manager &
+disown
 
 ######################################################################################
 # Messages
