fix remote bashlib to push error to calling script

diff --git a/module/remote b/module/remote
--- a/module/remote
+++ b/module/remote
@@ -131,6 +131,7 @@ remote() {
                     grep -Ev "$pattern" "$BASHLIB_HOME/$module"
                 fi
             done
+            printf '%s\n' "trap '' ERR" # disable trap here to allow pushing error to calling script
             (($# == 0)) || debug "Running: $*"
             (($# == 0)) || escape_args "$@"
             [ ! -p /dev/stdin ] || debug "Running piped command!"
