add filter command to tsv #91

diff --git a/module/table b/module/table
--- a/module/table
+++ b/module/table
@@ -48,11 +48,13 @@ for row in reader:
 #
 # To run multiple actions call it multiple times in a pipe.
 #
+# The **filter** command uses @check to do it's work so <type> <operator> <comparison> are all passed through.
+#
 # Usage:    <string> | tsv crop <num|name> <width>                  # crop column
 #           <string> | tsv sort <num|name> [numeric] [<options>]    # sort by column
 #           <string> | tsv reverse [<options>]                      # reverse order
 #           <string> | tsv to {csv|pprint} [<options>]              # convert
-#           <string> | tsv filter [<num|name> <operator> <value>]   # filter some rows
+#           <string> | tsv filter [<type> <num|name> <operator> <comparison>]   # filter some rows
 # Options:  --with-header              # keep first line as header in `sort`, `reverse`
 #           --remove-header            # remove first (header) line
 #           --colorize-line "<num|name>\t<operator>\t<value>\t<color>"  # multiple allowed
@@ -77,7 +79,31 @@ tsv() {
     is false -- "$removeHeader" || removeHeader="${removeHeader#*$'\n'}"
     case $cmd in
     filter)
-        echo "$input"
+        local header cols idx line
+        if is true -- "$withHeader"; then
+            header="$(head -1 <<<"$input")"
+            echo "$header"
+            input="$(tail -n +2 <<<"$input")"
+        fi
+        if (($# >= 2)); then
+            is integer --name=arguments --min=4 --max=5 --die -- $#
+            IFS=$'\t' read -r -a cols <<<"$header"
+            if is integer -- "$3"; then
+                idx=$(($2 - 1))
+            else
+                is set -- "$header" || die "Named columns only possible using --with-header option"
+                idx="$(array cols indexof "$3")" || die "Column [$3] not found in table"
+            fi
+            debug "filter $2 cols[$idx] $4 $5"
+            while IFS= read -r line; do
+                IFS=$'\t' read -r -a cols <<<"$line"
+                debug "check $2 \"${cols[idx]}\" \"$4\" \"$5\""
+                check $2 "${cols[idx]}" "$4" "$5" || continue
+                echo "$line"
+            done <<<"$input"
+        else
+            printf '%s' "$input"
+        fi
         ;;
     to)
         local format=$2
