new is/check validator use in core and output moved into core

diff --git a/core/output b/core/output
--- a/core/output
+++ b/core/output
@@ -11,14 +11,21 @@ source /dev/null
 # Show help page and exit
 # Usage:    help <heading> <usage> <options-spec> <details>
 help() {
-    heading "Hilfe: $1"
+    is integer --name=arguments --min=2 --max=4 --die -- $#
+    is set --name=heading --die -- "$1"
+    is set --name=usage --die -- "$2"
+    # processing
+    heading "$(gettext Help): $1"
     info "Usage: $2"
     echo ""
-    if [ -n "$3" ]; then
+    if is set -- "$3"; then
         option_help "$3"
         echo ""
     fi
-    echo "$4"
+    if is set -- "$4"; then
+        echo "$4"
+        echo
+    fi
     exit 0
 }
 
@@ -36,20 +43,21 @@ declare -Ag _log_active
 # _log_active[path]="<path> <level> <rotate> [<compress> [<cleanup>]]"
 
 # Additional logging (at the moment only into files).
-# After initialising a log using `start` the default output options will additionally write into log. But you can also specifically write t it using the log function.
+# After initializing a log using `start` the default output options will additionally write into log. But you can also specifically write t it using the log function.
 # Multiple log with different levels are possible.
-# Usage:    log start <file>        # no spaces in file path allowed
+# Usage:    log start <destination>                    # no spaces in file path allowed
 #           log <level> <message>
-#           log end <file>
+#           <message> | log <level>
+#           log end <destination>
 # Options:  -l, --level=<level>                 # level := debug info notice warn error critical
 #           # File logging:
 #           -r, --rotate=hourly|daily|weekly|monthly|<bytes>
 #           -c, --cleanup=<num>|<duration>
 #           -z, --compress
-# Files:    <file>[_<pattern>]                  # will contain the logs
+# Files:    <destination>[_<pattern>]                  # will contain the logs
 # Example:  # Format: <date> <time> <level> <message>
 #           2025-12-02 14:07:35 INFO Hello
-#           2025-12-02 14:10:04 ERROR Thius is only a test
+#           2025-12-02 14:10:04 ERROR This is only a test
 log() {
     # parameter parsing
     local level=1 rotate compress=0 cleanup text size
@@ -68,32 +76,24 @@ log() {
             fi
             shift 2
             ;;
-        -z | --compress)
-            compress=1
-            shift
-            ;;
-        -c | --cleanup)
-            cleanup="$(duration_format seconds "$2")"
-            shift 2
-            ;;
-        --)
-            shift
-            break
-            ;;
+        -z | --compress) compress=1 && shift ;;
+        -c | --cleanup) cleanup="$(duration_format seconds "$2")" && shift 2 ;;
+        --) shift && break ;;
         *) die "$(gettext "Unrecognized option"): $1" ;;
         esac
     done
-    [ -n "$rotate" ] || cleanup=""  # no cleanup if no rotate
-    [ -n "$rotate" ] || compress="" # no compress if no rotate
+    is integer --name=arguments --min=1 --max=2 --die -- $#
+    is enum --name=command --allow="start stop ${_log_level[*]}" --die -- "$1"
+    is empty -- "$rotate" && cleanup="" && compress="" || true # no cleanup/compress if no rotate
     # processing
     case $1 in
     start)
-        num_parameters --min=2 --max=2 --die="To start a new log a file path is needed as argument" "$@"
+        is set --name=destination --die -- "$2"
         [ -w "$2" ] || [ -w "$(dirname "$2")" ] || die "Could not write/create log under $2"
         hash _log_active set "$2" "$2 $level $rotate $compress $cleanup"
         ;;
     stop)
-        num_parameters --min=2 --max=2 --die="To end a log it'S file path is needed as argument" "$@"
+        is set --name=destination --die -- "$2"
         hash _log_active unset "$2"
         ;;
     debug | info | notice | warn | error | critical)
@@ -153,8 +153,6 @@ _log_manager() {
         done
     done
 }
-_log_manager &
-disown
 
 ######################################################################################
 # Messages
@@ -167,7 +165,8 @@ disown
 # Variable: $server
 heading() {
     local prefix=""
-    test -z "${server-}" || prefix="${server-} "
+    # shellcheck disable=SC2154
+    is empty -- "$server" || prefix="${server-} "
     printf "\n%s\n\n" "${CC_INVERS}$prefix${CC_RESET}${CC_HEADING}$(input "$@")...${CC_RESET}"
 }
 
@@ -178,7 +177,8 @@ heading() {
 critical() {
     local text
     text="$(input "$@")"
-    test -z "$text" || printf "%s\n" "${CC_CRITICAL}$text${CC_RESET}"
+    is set -- "$text" || return 0
+    printf "%s\n" "${CC_CRITICAL}$text${CC_RESET}"
     ((${#_log_active[@]} == 0)) || log critical "$text"
 }
 
@@ -189,7 +189,8 @@ critical() {
 error() {
     local text
     text="$(input "$@")"
-    test -z "$text" || printf "%s\n" "${CC_ERROR}$text${CC_RESET}"
+    is set -- "$text" || return 0
+    printf "%s\n" "${CC_ERROR}$text${CC_RESET}"
     ((${#_log_active[@]} == 0)) || log error "$text"
 }
 
@@ -197,10 +198,12 @@ error() {
 # Usage:    warn <message>
 #           <message> | warn
 # Stdout:   colored <string>
+# shellcheck disable=SC2120
 warn() {
     local text
     text="$(input "$@")"
-    test -z "$text" || printf "%s\n" "${CC_WARN}$text${CC_RESET}"
+    is set -- "$text" || return 0
+    printf "%s\n" "${CC_WARN}$text${CC_RESET}"
     ((${#_log_active[@]} == 0)) || log warn "$text"
 }
 
@@ -208,10 +211,12 @@ warn() {
 # Usage:    info <message>
 #           <message> | info
 # Stdout:   colored <string>
+# shellcheck disable=SC2120
 notice() {
     local text
     text="$(input "$@")"
-    test -z "$text" || printf "%s\n" "${CC_NOTICE}$text${CC_RESET}"
+    is set -- "$text" || return 0
+    printf "%s\n" "${CC_NOTICE}$text${CC_RESET}"
     ((${#_log_active[@]} == 0)) || log notice "$text"
 }
 
@@ -222,7 +227,8 @@ notice() {
 info() {
     local text
     text="$(input "$@")"
-    test -z "$text" || printf "%s\n" "$text"
+    is set -- "$text" || return 0
+    printf "%s\n" "$text"
     ((${#_log_active[@]} == 0)) || log info "$text"
 }
 
@@ -233,7 +239,8 @@ info() {
 ok() {
     local text
     text="$(input "$@")"
-    test -z "$text" || echo -e "${CC_OK}$text${CC_RESET}"
+    is set -- "$text" || return 0
+    echo -e "${CC_OK}$text${CC_RESET}"
     ((${#_log_active[@]} == 0)) || log notice "$text"
 }
 
@@ -244,7 +251,8 @@ ok() {
 invers() {
     local text
     text="$(input "$@")"
-    test -z "$text" || echo -e "${CC_INVERS}$text${CC_RESET}"
+    is set -- "$text" || return 0
+    echo -e "${CC_INVERS}$text${CC_RESET}"
     ((${#_log_active[@]} == 0)) || log info "$text"
 }
 
@@ -255,7 +263,8 @@ invers() {
 color() {
     local text
     text="$(input_args 1 "$@")"
-    test -z "$text" || echo -e "${CC_ERROR}$text${CC_RESET}"
+    is set -- "$text" || return 0
+    echo -e "${CC_ERROR}$text${CC_RESET}"
     ((${#_log_active[@]} == 0)) || log info "$text"
 }
 
@@ -307,6 +316,8 @@ urlencode() {
 # When printed to a terminal, it will erase everything from the current cursor position backward to the beginning of the line.
 # Usage:    erase_line
 erase_line() {
+    is integer --name=arguments --max=0 --die -- $#
+    # processing
     printf '%b' $'\e[1K\r'
 }
 
@@ -321,9 +332,12 @@ erase_line() {
 # Usage:    horizontal_line [<format>]
 # Output:   ────────── # over full width of terminal
 horizontal_line() {
+    is integer --name=arguments --max=1 --die -- $#
+    is empty -- "$1" || is enum --name=format --allow="light bold double half full"--die -- "$1"
+    # processing
     local char
     case $1 in
-    light) char="─" ;;
+    #light) char="─" ;; # is the default
     bold) char="━" ;;
     double) char="═" ;;
     half) char="▄" ;;
@@ -346,17 +360,20 @@ _spinner_pid=""
 # - `vertical`: ▏ ▎ ▍ ▌ ▋ ▊ ▉ █ ▉ ▊ ▋ ▌ ▍ ▎ ▏
 # - `bar`:      (as `vertical` but two characters wide)
 # - `fade`:     ░ ▒ ▓ █ ▓ ▒ ░
-# - `braile`:   ⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏ (default)
+# - `braille`:   ⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏ (default)
 # - `roll`:     ⠋ ⠙ ⠚ ⠞ ⠖ ⠦ ⠴ ⠲ ⠳ ⠓
 # - `moon`:     🌑 🌒 🌓 🌔 🌕 🌖 🌗 🌘
 # - `clock`:    🕐 🕑 🕒 🕓 🕔 🕕 🕖 🕗 🕘 🕙 🕚 🕛
 # - `weather`:  🌤 🌥 🌦 🌧 🌨 🌩 🌪
-# Usage:    spinner_start <format> <time>
+# Usage:    spinner_start <format> [<time>]
 #           # <format> see above
 #           # <time> 0.1 or more seconds (default 0.2)
 # TTY:      <symbol> with back-space so that cursor is always before it
 # Returns:   0 without doing anything if no `tput` and terminal available
 spinner_start() {
+    is integer --name=arguments --max=2 --die -- $#
+    is empty -- "$1" || is enum --name=format --allow="simple arrows vertical bar fade braille roll moon clock weather" --die -- "$1"
+    # processing
     if ! command -v tput >/dev/null 2>&1 || [ ! -t 2 ]; then
         debug "Disabled because tput and terminal is needed"
         return 0
@@ -367,11 +384,12 @@ spinner_start() {
     local chars=1
     local delay=${2:-0.2}
     case $format in
+    #simple) spinner='-\|/' ;; # is the default option, too
     arrows) spinner='→↑←↓' ;;
     vertical) spinner='▏▎▍▌▋▊▉█▉▊▋▌▍▎▏' ;;
     bar) spinner='▏ ▎ ▍ ▌ ▋ ▊ ▉ █ █▏█▎█▍█▌█▋█▊█▉███▉█▊█▋█▌█▍█▎█▏█ ▉ ▊ ▋ ▌ ▍ ▎ ▏ ' && chars=2 && size=2 ;;
     fade) spinner=' ░▒▓█▓▒░' ;;
-    braile) spinner='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' ;;
+    braille) spinner='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' ;;
     roll) spinner='⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓' ;;
     moon) spinner='🌑🌒🌓🌔🌕🌖🌗🌘' && size=2 ;;
     clock) spinner='🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛' && size=2 ;;
@@ -397,6 +415,8 @@ spinner_start() {
 # Call this after @spinner_start to stop it. It has to be called within the same thread!
 # Usage:    spinner_stop
 spinner_stop() {
+    is integer --name=arguments --max=0 --die -- $#
+    # processing
     [ -n "$_spinner_pid" ] || return # spinner not started
     kill "$_spinner_pid" >/dev/null 2>&1
     wait "$_spinner_pid" 2>/dev/null
diff --git a/core/validator b/core/validator
--- a/core/validator
+++ b/core/validator
@@ -7,32 +7,44 @@
 ######################################################################################
 
 # Validate and sanitize values.
-# Every parameter should be checked to prevent failure later in the code. For such checks you run it with the `--die` option to stop processing if wrong.
+# This validation is possible using the `check` and @is function.
+# - `check` should be used for sanitize because it will output the value
+# - @is should be used for checking only validity or stop processing on problem because no value is output
+#
+# Every parameter should be checked to prevent failure later in the code.
+# For such checks you run it with the `--die` option to stop processing if wrong.
 # But you can also use it in the program flow without that and use it's return status to check if it 0=ok or 1=failed.
+#
+# Because the values may start with an dash you should always put it at the end after '--' to prevent parsing it as option.
+#
 # The following checks are implemented:
 # - `set` will fail if no value given
 # - `empty` will fail if not empty like ""
 # - `bool` will transform the value to `1` or `0` and allows: true/false, t/f, 1/0, yes/no, y/j/n, ja/nein, ""
 # - `integer` will check for a number maybe within a range
 # - `float` will check for a number maybe within a range
-# Usage:    is <check> <value> [options]
-# Options:  d, die              # stop with error instead of return state
-#           n, name=<string>    # name the variable for the `die` message
+# - `enum' will check against valid words using `--allow="word1 word2"`
+# - `length` check that the length is within range (like integer)
+#
+# Usage:    check <check> [options] -- <value>
+# Options:  d, die              # used in @is to stop with error instead of return state
+#           n, name=<string>    # used in @is to display variable name in `die` message
 #           s, sanitize         # for integer
 #           min=<num>           # for integer
 #           max=<num>           # for integer
+#           allow=<words>       # for enum (space separated)
 # Output:   <value>             # may be sanitized
 # Exit:     with message if incorrect value
 # Example:  # check arguments
-#           is --name=arguments integer $# --min=1 --max=2
-#           name="$(is --name=age integer "$1" --sanitize --min=0)"
-#           init="$(is --name=init bool "$1")"
+#           check integer --name=arguments --max=2 $# >/dev/null # mostly only check max, if all args are checked separately
+#           name="$(check integer --name=age --sanitize --min=0 -- "$1")"
+#           init="$(check bool --name=init "$1")"
 #           # use in code
-#           if is integer age --min=18; then
-is() {
+#           if check integer age --min=18 -- "$1" >/dev/null; then
+check() {
     # parameter parsing
-    eval set -- "$(option_parse $'n name +\nd die -\ns sanitize -\n- min +\n- max +' "$@")"
-    local name die sanitize min max
+    eval set -- "$(option_parse $'n name +\nd die -\ns sanitize -\n- min +\n- max +\n- allow +' "$@")"
+    local name die sanitize min max allow
     # shellcheck disable=SC2015
     # shellcheck disable=SC2059
     while true; do
@@ -42,13 +54,15 @@ is() {
         -s | --sanitize) sanitize=1 && shift ;;
         --min) [[ "$2" =~ ^[-+]?[0-9]+([.][0-9]+)?$ ]] && min="$2" && shift 2 || die "$(printf "$(gettext "Parameter %s needs number")" min)" ;;
         --max) [[ "$2" =~ ^[-+]?[0-9]+([.][0-9]+)?$ ]] && max="$2" && shift 2 || die "$(printf "$(gettext "Parameter %s needs number")" max)" ;;
+        --allow) [ -n "$2" ] && allow="$2" && shift 2 || die "$(gettext "A list of words is needed")" ;;
         --) shift && break ;;
         *) die "$(gettext "Unrecognized option"): $1" ;;
         esac
     done
     name="${name:-argument}"
     # processing
-    local usage="$(gettext "Incorrect call"): is <check> <value> [options]"
+    local usage
+    usage="$(gettext "Incorrect call"): is <check> <value> [options]"
     # shellcheck disable=SC2015
     [ -n "$1" ] && local check="$1" || die "$usage"
     local val="$2" res="$2"
@@ -56,12 +70,12 @@ is() {
     case $check in
     set)
         if [ -z "$val" ]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be set with a value.')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be set with a value')"
         fi
         ;;
     empty)
         if [ -n "$val" ]; then
-            [ -n "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be empty but has »${val}«.')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be empty but has »${val}«')"
         fi
         ;;
     bool)
@@ -70,7 +84,7 @@ is() {
         elif [[ -z "$val" || "${val,,}" =~ ^(false|f|0|no|n|nein)$ ]]; then
             res=0
         else
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The value »${val}« for "$name" could not be read as true or false.')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The value »${val}« for "$name" could not be read as true or false')"
         fi
         ;;
     integer)
@@ -78,19 +92,23 @@ is() {
             [[ "$val" =~ ^(-?[0-9]+) ]] && res="${BASH_REMATCH[1]}" || true
         fi
         if [[ ! "$res" =~ ^-?[0-9]+$ ]]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be an integer but »${val}« was given.')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be an integer but »${val}« was given')"
         fi
-        if [[ -n "$min" && -n "$max" ]]; then
+        if [[ -n "$min" ]] && [[ "$min" == "$max" ]]; then
+            if ((res != min)); then
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')"
+            fi
+        elif [[ -n "$min" && -n "$max" ]]; then
             if ((res < min || res > max)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given.')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')"
             fi
         elif [[ -n "$min" ]]; then
             if ((res < min)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given.')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')"
             fi
         elif [[ -n "$max" ]]; then
             if ((res > max)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to not more than $max but »${val}« was given.')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')"
             fi
         fi
         ;;
@@ -99,25 +117,90 @@ is() {
             [[ "$val" =~ ^(-?[0-9]+([.][0-9]+)?) ]] && res="${BASH_REMATCH[1]}" || true
         fi
         if [[ ! "$res" =~ ^-?[0-9]+([.][0-9]+)?$ ]]; then
-            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be a float but »${val}« was given.')"
+            [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be a float but »${val}« was given')"
         fi
-        if [[ -n "$min" && -n "$max" ]]; then
+        if [[ -n "$min" ]] && [[ "$min" == "$max" ]]; then
+            if ((res != min)); then
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be exactly $min but »${val}« was given')"
+            fi
+        elif [[ -n "$min" && -n "$max" ]]; then
             if ((res < min || res > max)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given.')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to be between $min and $max but »${val}« was given')"
             fi
         elif [[ -n "$min" ]]; then
             if ((res < min)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given.')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to at least $min but »${val}« was given')"
             fi
         elif [[ -n "$max" ]]; then
             if ((res > max)); then
-                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to not more than $max but »${val}« was given.')"
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The "$name" has to not be more than $max but »${val}« was given')"
             fi
         fi
         ;;
-    *) die "$(eval_gettext 'A check named ${check} is not defined.')" ;;
+    length)
+        val=${#val}
+        if [[ -n "$min" ]] && [[ "$min" == "$max" ]]; then
+            if ((res != min)); then
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be exactly $min but »${res}« is $val characters long')"
+            fi
+        elif [[ -n "$min" && -n "$max" ]]; then
+            if ((val < min || val > max)); then
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be between $min and $max but »${res}« is $val characters long')"
+            fi
+        elif [[ -n "$min" ]]; then
+            if ((val < min)); then
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be at least $min but »${res}« is $val characters long')"
+            fi
+        elif [[ -n "$max" ]]; then
+            if ((val > max)); then
+                [ -z "$die" ] && return 1 || die "$(eval_gettext 'The length of "$name" has to be not more than $max but »${res}« is $val characters long')"
+            fi
+        fi
+        ;;
+    enum)
+        [ -n "$allow" ] || die "$(gettext "A list with --allow=<words> is needed for enum check")"
+        if [[ " $allow " != *" $val "* ]]; then
+            [ -z "$die" ] && return 1 || die "$(eval_gettext '"$name" is set to "${val}" but has to be one of: $allow')"
+        fi
+        ;;
+    *) die "$(eval_gettext 'A check named ${check} is not defined')" ;;
     esac
     echo "$res"
+}
+
+# Validate and sanitize values.
+# This validation is possible using the @check and `is` function.
+# - @check should be used for sanitize because it will output the value
+# - `is` should be used for checking only validity or stop processing on problem because no value is output
+#
+# Every parameter should be checked to prevent failure later in the code.
+# For such checks you run it with the `--die` option to stop processing if wrong.
+# But you can also use it in the program flow without that and use it's return status to check if it 0=ok or 1=failed.
+#
+# Because the values may start with an dash you should always put it at the end after '--' to prevent parsing it as option.
+#
+# The following checks are implemented:
+# - `set` will fail if no value given
+# - `empty` will fail if not empty like ""
+# - `bool` will transform the value to `1` or `0` and allows: true/false, t/f, 1/0, yes/no, y/j/n, ja/nein, ""
+# - `integer` will check for a number maybe within a range
+# - `float` will check for a number maybe within a range
+# - `enum' will check against valid words using `--allow="word1 word2"`
+# - `length` check that the length is within range (like integer)
+#
+# Usage:    is <check> [options] -- <value>
+# Options:  d, die              # stop with error instead of return state
+#           n, name=<string>    # name the variable for the `die` message
+#           min=<num>           # for integer
+#           max=<num>           # for integer
+#           allow=<words>       # for enum (space separated)
+# Exit:     with message if incorrect value
+# Example:  # check arguments
+#           is integer --name=arguments --max=2 $# # mostly only check max, if all args are checked separately
+#           # use in code
+#           if is integer age --min=18 -- "$1"; then
+is() {
+    check "$@" >/dev/null
 }
 
 # Deprecated: Check that a specific number of parameters are given
@@ -127,7 +210,7 @@ is() {
 #           --max <int>     # not more than <int> elements are allowed
 #           --die <string>  # exit with this message if not
 num_parameters() {
-    _deprecated "Use: is integer $# --min=<val> --max=<val>"
+    _deprecated "Use: is integer $# --min=<val> --max=<val>" warn
     # parameter parsing
     eval set -- "$(option_parse $'- min +\n- max +\n- die +' "$@")"
     local min max die
@@ -168,8 +251,8 @@ num_parameters() {
 # Usage:    is_empty <var>
 # Status:   0 => true
 is_empty() {
-    _deprecated "Use: is empty <value>"
-    is empty "$1"
+    _deprecated "Use: is empty -- <value>"
+    is empty -- "$1"
 }
 
 # Deprecated: Test if given value is an integer
@@ -177,8 +260,8 @@ is_empty() {
 # Usage:    is_integer <value>
 # Status:   0 => is integer
 is_integer() {
-    _deprecated "Use: is integer <value>"
-    is integer "$1"
+    _deprecated "Use: is integer <value>" warn
+    is integer -- "$1"
 }
 
 # Deprecated: Test if given value is an float
@@ -186,8 +269,8 @@ is_integer() {
 # Usage:    is_float <value>
 # Status:   0 => is float
 is_float() {
-    _deprecated "Use: is float <value>"
-    is float "$1"
+    _deprecated "Use: is float -- <value>" warn
+    is float -- "$1"
 }
 
 ######################################################################################
@@ -199,8 +282,10 @@ is_float() {
 # Output:   <string>
 # See:      https://stackoverflow.com/a/3352015
 trim_start() {
+    is integer --name=arguments --max=2 --die -- $#
     local str="${1-}"
     local char="${2:-[:space:]}"
+    # processing
     # shellcheck disable=SC2295
     echo "${str#"${str%%[!$char]*}"}"
 }
@@ -210,8 +295,10 @@ trim_start() {
 # Output:   <string>
 # See:      https://stackoverflow.com/a/3352015
 trim_end() {
+    is integer --name=arguments --max=2 --die -- $#
     local str="${1:-}"
     local char="${2:-[:space:]}"
+    # processing
     # shellcheck disable=SC2295
     echo "${str%"${str##*[!$char]}"}"
 }
@@ -221,6 +308,8 @@ trim_end() {
 # Output:   <string>
 # See:      https://stackoverflow.com/a/3352015
 trim() {
+    is integer --name=arguments --max=2 --die -- $#
+    # processing
     trim_end "$(trim_start "$1" "$2")" "$2"
 }
 
@@ -230,8 +319,10 @@ trim() {
 #           <string> | to_alphanum
 # Output:   <alnum>
 to_alphanum() {
+    is integer --name=arguments --max=1 --die -- $#
     local text
     text="$(input "$@")"
+    # processing
     echo "${text//[^a-zA-Z0-9_]/_}"
 }
 
@@ -239,7 +330,9 @@ to_alphanum() {
 # Usage:    value_if_variable <name>
 # Output:   <string>
 value_if_variable() {
+    is integer --name=arguments --max=2 --die -- $#
     local _name="$1"
+    # processing
     if [[ "$_name" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] &&
         [ -n "${!_name-}" ]; then
         echo "${!_name}"
